package Views;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import Controllers.PhieunhapController;
import Controllers.LonhapController;

import Models.Thuoc;
import Models.LoNhap;
import Models.Donvitinh;
import Models.Phieunhap;
import Models.ChitietPhieunhap;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

public class ChitietPhieunhapView extends JFrame {

    private int maPhieunhap;
    PhieunhapController pnCtrl = new PhieunhapController();
    private DefaultTableModel modelCTPN;
    private int indexOfList;

    public ChitietPhieunhapView() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblCTPN.setDefaultRenderer(String.class, centerRenderer);
        ((DefaultTableCellRenderer) tblCTPN.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tblCTPN.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        tblCTPN.getTableHeader().setOpaque(false);
        tblCTPN.getTableHeader().setBackground(Color.YELLOW);
        txtMaPN.setEditable(false);
        txtDongia.setEditable(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if (t instanceof ChitietPhieunhap) {
                ChitietPhieunhap ctpn = (ChitietPhieunhap) t;
                String soluong = ctpn.getSoluong() + " : " + ctpn.getThuoc().getDonvitinh().getTenDonvitinh();
                model.addRow(new Object[]{
                    ctpn.getLoNhap().getMaLo(), ctpn.getThuoc().getMaThuoc(), ctpn.getThuoc().getTenThuoc(), ctpn.getThuoc().getDonvitinh().getTenDonvitinh(), soluong, ctpn.getDongia()
                });

            }
        }
    }

    public void reset() {
        modelCTPN = (DefaultTableModel) tblCTPN.getModel();
        List<ChitietPhieunhap> ctpn;
        ctpn = pnCtrl.layDanhsachChitietPhieunhap(maPhieunhap);
        this.showData(ctpn, modelCTPN);
    }

    public void setVariable(int _mpn) {
        this.maPhieunhap = _mpn;
        txtMaPN.setText(String.valueOf(this.maPhieunhap));

        List<Thuoc> dst;
        dst = PhieunhapController.layDanhSachThuoc();
        for (Thuoc t : dst) {
            if (t instanceof Thuoc) {
                Thuoc th = (Thuoc) t;
                cbbThuoc.addItem(String.valueOf(th.getMaThuoc()) + " - " + th.getTenThuoc());
            }
        }
        this.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaPN = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTPN = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbThuoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinSoluong = new com.toedter.components.JSpinField();
        jLabel4 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        txtMaLN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbNhaCungCap = new javax.swing.JComboBox<>();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbbDVT = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMaPN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDongia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(153, 51, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Chi tiết phiếu nhập");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các lô nhập", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        tblCTPN.setBackground(new java.awt.Color(204, 255, 255));
        tblCTPN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lô nhập", "Mã thuốc", "Tên thuốc", "Đơn vị", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTPN.setRowHeight(30);
        tblCTPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTPNMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTPN);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Ðơn vị:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Đơn giá:");

        cbbThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbThuoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThuocItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Chọn thuốc:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Mã lô nhập:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Số lượng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Mã phiếu nhập:");

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 204, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(204, 0, 0));
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        txtMaLN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Chọn nhà cung cấp:");

        cbbNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbNhaCungCap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhaCungCapItemStateChanged(evt);
            }
        });

        cbbNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhanVienItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Nhân viên lập");

        cbbDVT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbDVT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDVTItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(btnThem)
                                .addGap(52, 52, 52)
                                .addComponent(btnSua)
                                .addGap(52, 52, 52)
                                .addComponent(btnXoa)
                                .addGap(52, 52, 52)
                                .addComponent(btnQuayLai)))
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbThuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtMaLN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDongia)
                                    .addComponent(cbbNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinSoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnQuayLai))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
//        int input = JOptionPane.showConfirmDialog(null,
//                "Bạn có chắc muốn xóa lô nhập này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
//        if (input == 0) {
//            String maThuoc = cbbThuoc.getSelectedItem().toString().split(" - ")[0];
//            String maLo1 = cbb.getSelectedItem().toString().split(" - ")[0];
//            String maLo2 = maLo1.toString().split(": ")[1];
//
//            ChitietPhieunhapView ctpn = new ChitietPhieunhapView(maPhieunhap, maThuoc, maLo2, 0, 0, false);
//            pnCtrl.xoaChitietPhieunhap(ctpn);
//            this.reset();
//        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        String maNV = cbbNhanVien.getSelectedItem().toString().split(" - ")[0];
//        String maNCC = cbbNhaCungCap.getSelectedItem().toString().split(" - ")[0];
//        String maThuoc = cbbThuoc.getSelectedItem().toString().split(" - ")[0];
//        String maLo = txtMaLN.getText();
//        
//        ChitietPhieunhapView cthd = new ChitietPhieunhapView(this.maPhieunhap, Integer.parseInt(maThuoc), Integer.parseInt(maLo), Integer.valueOf(spinSoluong.getValue()), Float.parseFloat(txtDongia.getText()), false);
//
//        hdctr.themCTHD(cthd);
//
//        this.reset();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
//        String maThuoc = cbbThuoc.getSelectedItem().toString().split(" - ")[0];
//        String maLo1 = comboLonhap.getSelectedItem().toString().split(" - ")[0];
//        String maLo2 = maLo1.toString().split(": ")[1];
//        ChitietPhieunhapView cthd = new ChitietPhieunhapView(maHoadon, Integer.parseInt(maThuoc), Integer.parseInt(maLo2), Integer.valueOf(spinSoluong.getValue()), Float.parseFloat(txtDongia.getText()), false);
//        hdctr.capnhatCTHD(cthd);
//        this.reset();
//
//        LonhapController lnctr = new LonhapController();
//        LoNhap ln = new LoNhap();
//        ln = lnctr.layLoNhap(Integer.parseInt(maLo2));
//        comboLonhap.removeAllItems();
//        comboLonhap.addItem("Mã lô: " + ln.getMaLo() + " - Số lượng còn lại: " + ln.getSoluongConlai());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cbbThuocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThuocItemStateChanged
        // TODO add your handling code here:
        Donvitinh dvt = new Donvitinh();
        String maThuoc = cbbThuoc.getSelectedItem().toString().split(" - ")[0];

//        dvt = hdctr.layDonvitinh(Integer.valueOf(maThuoc));
//        txtDonvi.setText(dvt.getTenDonvitinh());
//
//        Thuoc thuoc = new Thuoc();
//
//        thuoc = hdctr.layGiathuoc(Integer.valueOf(maThuoc));
//        txtDongia.setText(String.valueOf(thuoc.getGiaBan()));
//
//        comboLonhap.removeAllItems();
//        List<LoNhap> dsln;
//        dsln = hdctr.layDanhSachLonhap(Integer.valueOf(spinSoluong.getValue()), Integer.valueOf(maThuoc));
//        for (LoNhap t : dsln) {
//            if (t instanceof LoNhap) {
//                LoNhap ln = (LoNhap) t;
//                comboLonhap.addItem("Mã lô: " + String.valueOf(ln.getMaLo()) + " - Số lượng còn lại: " + ln.getSoluongConlai());
//            }
//        }
    }//GEN-LAST:event_cbbThuocItemStateChanged

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tblCTPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTPNMouseClicked
        // TODO add your handling code here:
//        JTable source = (JTable) evt.getSource();
//        indexOfList = source.rowAtPoint(evt.getPoint());
//        String s1 = source.getModel().getValueAt(indexOfList, 0).toString();
//        String s2 = source.getModel().getValueAt(indexOfList, 1).toString();
//        String s3 = source.getModel().getValueAt(indexOfList, 2).toString();
//        String s4 = source.getModel().getValueAt(indexOfList, 3).toString();
//        String s5 = source.getModel().getValueAt(indexOfList, 4).toString();
//
//        cbbThuoc.setSelectedItem(s1 + " - " + s2);
//        String soluong = s4.split(" : ")[0];
//        spinSoluong.setValue(Integer.parseInt(soluong));
//        LonhapController lnctr = new LonhapController();
//        LoNhap ln = new LoNhap();
//        ln = lnctr.layLoNhap(Integer.parseInt(s3));
//        comboLonhap.removeAllItems();
//        comboLonhap.addItem("Mã lô: " + ln.getMaLo() + " - Số lượng còn lại: " + ln.getSoluongConlai());
//        txtDongia.setText(s5);
//
//        Donvitinh dvt = new Donvitinh();
//        String maThuoc = cbbThuoc.getSelectedItem().toString().split(" - ")[0];
//
//        dvt = hdctr.layDonvitinh(Integer.valueOf(maThuoc));
//        txtDonvi.setText(dvt.getTenDonvitinh());
//
//        btnSua.setEnabled(true);
//        btnXoa.setEnabled(true);
//        cbbThuoc.setEnabled(false);
//        comboLonhap.setEnabled(false);


    }//GEN-LAST:event_tblCTPNMouseClicked

    private void cbbNhaCungCapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhaCungCapItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNhaCungCapItemStateChanged

    private void cbbNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhanVienItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNhanVienItemStateChanged

    private void cbbDVTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDVTItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDVTItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChitietHoadonView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDVT;
    private javax.swing.JComboBox<String> cbbNhaCungCap;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JComboBox<String> cbbThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.components.JSpinField spinSoluong;
    private javax.swing.JTable tblCTPN;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMaLN;
    private javax.swing.JTextField txtMaPN;
    // End of variables declaration//GEN-END:variables
}
