/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import Controllers.HoadonController;
import Controllers.LonhapController;

import Models.ChitietHoadon;
import Models.Thuoc;
import Models.Hoadon;
import Models.Khachhang;

import Models.LoNhap;
import Models.Donvitinh;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.BaseFont;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author TinhBui
 */
public class ChitietHoadonView extends javax.swing.JFrame {

    /**
     * Creates new form CTHD
     */
    private int maHoadon;
    HoadonController hdctr = new HoadonController();
    private DefaultTableModel modelCTHD;
    private int indexOfList;
    public static File fontFile = new File("fonts/vuTimes.ttf");

    public ChitietHoadonView() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        dsCTHD.setDefaultRenderer(String.class, centerRenderer);
        ((DefaultTableCellRenderer) dsCTHD.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        dsCTHD.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        dsCTHD.getTableHeader().setOpaque(false);
        dsCTHD.getTableHeader().setBackground(Color.YELLOW);
        txtMHD.setEditable(false);
        txtDonvi.setEditable(false);
        txtDongia.setEditable(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        if (!DangnhapView.quyenLogin.getChitietQuyen().contains("qlHoaDon")) {
            btnThem.setEnabled(false);
        }
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if (t instanceof ChitietHoadon) {
                ChitietHoadon cthd = (ChitietHoadon) t;
                String soluong = cthd.getSoluong() + " : " + cthd.getTenDonvitinh();

                model.addRow(new Object[]{
                    cthd.getMaThuoc(), cthd.getTenThuoc(), cthd.getMaLo(), soluong, cthd.getDongia()
                });

            }
        }
    }

    public void reset() {
        modelCTHD = (DefaultTableModel) dsCTHD.getModel();
        List<ChitietHoadon> cthd;
        cthd = hdctr.layDanhsachCTHD(maHoadon);
        this.showData(cthd, modelCTHD);
    }

    public void setVariable(int mhd) {
        this.maHoadon = mhd;
        txtMHD.setText(String.valueOf(this.maHoadon));

        List<Thuoc> dst;
        dst = hdctr.layDanhSachThuoc();
        for (Thuoc t : dst) {
            if (t instanceof Thuoc) {
                Thuoc th = (Thuoc) t;
                comboThuoc.addItem(String.valueOf(th.getMaThuoc()) + " - " + th.getTenThuoc());
            }
        }

        this.reset();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMHD = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dsCTHD = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboThuoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboLonhap = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDonvi = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        spinSoluong = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMHDActionPerformed(evt);
            }
        });

        txtDongia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_forever_30px_1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Chi tiết hóa đơn");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thuốc trong hóa đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        dsCTHD.setBackground(new java.awt.Color(204, 255, 255));
        dsCTHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dsCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Lô nhập", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dsCTHD.setRowHeight(30);
        dsCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dsCTHD);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Ðơn vị:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Đơn giá:");

        comboThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboThuoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboThuocItemStateChanged(evt);
            }
        });
        comboThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboThuocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Chọn thuốc:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Chọn lô nhập:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Số lượng:");

        comboLonhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboLonhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLonhapActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Mã hóa đơn:");

        txtDonvi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_database_restore_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-30.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_replay_30px.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_downloads_30px.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        spinSoluong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboThuoc, 0, 225, Short.MAX_VALUE)
                                .addComponent(txtMHD))
                            .addComponent(spinSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtDongia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtDonvi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(comboLonhap, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnThem)
                .addGap(52, 52, 52)
                .addComponent(btnLammoi)
                .addGap(52, 52, 52)
                .addComponent(btnSua)
                .addGap(52, 52, 52)
                .addComponent(btnXoa)
                .addGap(52, 52, 52)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnIn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboLonhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(spinSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnBack)
                    .addComponent(btnLammoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn xóa thuốc này khỏi hóa đơn không không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            String maThuoc = comboThuoc.getSelectedItem().toString().split(" - ")[0];
            String maLo1 = comboLonhap.getSelectedItem().toString().split(" - ")[0];
            String maLo2 = maLo1.toString().split(": ")[1];

            ChitietHoadon cthd = new ChitietHoadon(maHoadon, Integer.parseInt(maThuoc), Integer.parseInt(maLo2), 0, 0, false);
            try {
                hdctr.xoaCTHD(cthd);
                JOptionPane.showMessageDialog(null, "Xóa chi tiết hóa đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi không thể xóa chi tiết hóa đơn", "Thông báo", JOptionPane.ERROR_MESSAGE);

            }

            this.reset();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maThuoc = comboThuoc.getSelectedItem().toString().split(" - ")[0];
        String maLo1 = comboLonhap.getSelectedItem().toString().split(" - ")[0];
        String maLo2 = maLo1.toString().split(": ")[1];

        ChitietHoadon cthd = new ChitietHoadon(this.maHoadon, Integer.parseInt(maThuoc), Integer.parseInt(maLo2), Integer.valueOf(spinSoluong.getValue().toString()), Float.parseFloat(txtDongia.getText()), false);

        try {
            hdctr.themCTHD(cthd);
            JOptionPane.showMessageDialog(null, "Thêm chi tiết hóa đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi không thể thêm chi tiết hóa đơn", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

        this.reset();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maThuoc = comboThuoc.getSelectedItem().toString().split(" - ")[0];
        String maLo1 = comboLonhap.getSelectedItem().toString().split(" - ")[0];
        String maLo2 = maLo1.toString().split(": ")[1];
        ChitietHoadon cthd = new ChitietHoadon(maHoadon, Integer.parseInt(maThuoc), Integer.parseInt(maLo2), Integer.valueOf(spinSoluong.getValue().toString()), Float.parseFloat(txtDongia.getText()), false);
        try {
            hdctr.capnhatCTHD(cthd);
            JOptionPane.showMessageDialog(null, "Sửa chi tiết hóa đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi không thể sửa chi tiết hóa đơn", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

        this.reset();

        LonhapController lnctr = new LonhapController();
        LoNhap ln = new LoNhap();
        ln = lnctr.layLoNhap(Integer.parseInt(maLo2));
        comboLonhap.removeAllItems();
        comboLonhap.addItem("Mã lô: " + ln.getMaLo() + " - Số lượng còn lại: " + ln.getSoluongConlai());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void comboThuocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboThuocItemStateChanged
        // TODO add your handling code here:
        Donvitinh dvt = new Donvitinh();
        String maThuoc = comboThuoc.getSelectedItem().toString().split(" - ")[0];

        dvt = hdctr.layDonvitinh(Integer.valueOf(maThuoc));
        txtDonvi.setText(dvt.getTenDonvitinh());

        Thuoc thuoc = new Thuoc();

        thuoc = hdctr.layGiathuoc(Integer.valueOf(maThuoc));
        txtDongia.setText(String.valueOf(thuoc.getGiaBan()));

        comboLonhap.removeAllItems();
        List<LoNhap> dsln;
        dsln = hdctr.layDanhSachLonhap(Integer.valueOf(spinSoluong.getValue().toString()), Integer.valueOf(maThuoc));
        for (LoNhap t : dsln) {
            if (t instanceof LoNhap) {
                LoNhap ln = (LoNhap) t;
                comboLonhap.addItem("Mã lô: " + String.valueOf(ln.getMaLo()) + " - Số lượng còn lại: " + ln.getSoluongConlai());
            }
        }
    }//GEN-LAST:event_comboThuocItemStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void dsCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsCTHDMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        indexOfList = source.rowAtPoint(evt.getPoint());
        String s1 = source.getModel().getValueAt(indexOfList, 0).toString();
        String s2 = source.getModel().getValueAt(indexOfList, 1).toString();
        String s3 = source.getModel().getValueAt(indexOfList, 2).toString();
        String s4 = source.getModel().getValueAt(indexOfList, 3).toString();
        String s5 = source.getModel().getValueAt(indexOfList, 4).toString();

        comboThuoc.setSelectedItem(s1 + " - " + s2);
        String soluong = s4.split(" : ")[0];
        spinSoluong.setValue(Integer.parseInt(soluong));
        LonhapController lnctr = new LonhapController();
        LoNhap ln = new LoNhap();
        ln = lnctr.layLoNhap(Integer.parseInt(s3));
        comboLonhap.removeAllItems();
        comboLonhap.addItem("Mã lô: " + ln.getMaLo() + " - Số lượng còn lại: " + ln.getSoluongConlai());
        txtDongia.setText(s5);

        Donvitinh dvt = new Donvitinh();
        String maThuoc = comboThuoc.getSelectedItem().toString().split(" - ")[0];

        dvt = hdctr.layDonvitinh(Integer.valueOf(maThuoc));
        txtDonvi.setText(dvt.getTenDonvitinh());

        if (DangnhapView.quyenLogin.getChitietQuyen().contains("qlHoaDon")) {
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }

        comboThuoc.setEnabled(false);
        comboLonhap.setEnabled(false);


    }//GEN-LAST:event_dsCTHDMouseClicked

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn tải lại trang hay không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            comboLonhap.setEnabled(true);
            comboThuoc.setEnabled(true);

            this.reset();
        }

    }//GEN-LAST:event_btnLammoiActionPerformed

    private void comboThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboThuocActionPerformed

    private void comboLonhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLonhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLonhapActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        String PATH = "";
        String name = "";

        JFileChooser j = new JFileChooser();
//        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(j);
        if (x == JFileChooser.APPROVE_OPTION) {
            name = j.getSelectedFile().getName();
            PATH = j.getSelectedFile().getParentFile().getPath();
//            PATH = j.getSelectedFile().getPath();
        }

        if (PATH.endsWith("\\")) {
            PATH = PATH + name + ".pdf";

        } else {
            PATH = PATH + "\\" + name + ".pdf";
        }

        Document doc = new Document();

        try {
//            File file = new File(fileChoose.getSelectedFile().toString());
            PdfWriter.getInstance(doc, new FileOutputStream(PATH));

            doc.open();

//            BaseFont baseFont = BaseFont.createFont(/*"resources/ARIAL.TTF"*/"c:/Windows/Fonts/vuTimes.ttf", BaseFont.IDENTITY_H, true);
//            com.itextpdf.text.Font font = FontFactory.getFont("D:/vuArial.ttf", 15);
            Paragraph title = new Paragraph("HOA DON", FontFactory.getFont(FontFactory.TIMES_ROMAN, 22, Font.BOLD, new CMYKColor(0, 255, 255, 17)));

            title.setAlignment(WIDTH);
            doc.add(title);

//            doc.add(new Paragraph("Đại học bách khoa Hà Nội", font));
            Hoadon hd = new Hoadon();
            hd = hdctr.layThongTinHoaDon(maHoadon);
            Khachhang kh = new Khachhang();
            kh = hdctr.layThongKhachhang(maHoadon);

            SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String formatted = format1.format(hd.getNgayLap().getTime());

            Paragraph tenNhanvien = new Paragraph("\nNguoi lap: " + hd.getTenNhanvien(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.ITALIC, new CMYKColor(0, 255, 255, 255)));
            Paragraph tenKhachhang = new Paragraph("Khách hàng: " + hd.getTenKhachhang() + ";     Gioi tính: " + kh.getGioitinh() + ";     So dien thoại: " + kh.getSoDienthoai(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.ITALIC, new CMYKColor(0, 255, 255, 255)));
            Paragraph diaChi = new Paragraph("Dia chi: " + kh.getDiaChi(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.ITALIC, new CMYKColor(0, 255, 255, 255)));
            Paragraph ngayLap = new Paragraph("Ngày lap: " + formatted, FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.ITALIC, new CMYKColor(0, 255, 255, 255)));

            doc.add(tenNhanvien);
            doc.add(tenKhachhang);
            doc.add(diaChi);
            doc.add(ngayLap);

//            Paragraph stt = new Paragraph("STT", FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            PdfPTable tbl = new PdfPTable(5);
            tbl.setSpacingBefore(30);
            tbl.setSpacingAfter(30);
            tbl.setHeaderRows(1);
            tbl.setWidths(new int[]{1, 3, 2, 2, 3});

            Paragraph stt = new Paragraph("STT", FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph thuoc = new Paragraph("Ten thuoc", FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph sl = new Paragraph("So luong", FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph dg = new Paragraph("Don gia", FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph thanhtien = new Paragraph("Thành tien", FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));

            tbl.addCell(stt);
            tbl.addCell(thuoc);
            tbl.addCell(sl);
            tbl.addCell(dg);
            tbl.addCell(thanhtien);

            for (int i = 0; i < dsCTHD.getRowCount(); i++) {
                String tenThuoc = dsCTHD.getValueAt(i, 1).toString();
                String soLuong = dsCTHD.getValueAt(i, 3).toString();
                String donGia = dsCTHD.getValueAt(i, 4).toString();
                String slthuoc = soLuong.split(" : ")[0];
                float thanhTien = (Integer.parseInt(slthuoc)) * (Float.parseFloat(donGia));
                Paragraph tt = new Paragraph(tenThuoc, FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.ITALIC, new CMYKColor(0, 0, 0, 255)));
                Paragraph sl1 = new Paragraph(slthuoc, FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.ITALIC, new CMYKColor(0, 0, 0, 255)));
                Paragraph dg1 = new Paragraph(donGia, FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.ITALIC, new CMYKColor(0, 0, 0, 255)));
                Paragraph tt1 = new Paragraph(String.valueOf(thanhTien), FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.ITALIC, new CMYKColor(0, 0, 0, 255)));

                tbl.addCell(String.valueOf(i + 1));
                tbl.addCell(tt);
                tbl.addCell(sl1);
                tbl.addCell(dg1);
                tbl.addCell(tt1);

            }
            doc.add(tbl);
            Paragraph tongtien = new Paragraph("Tong tien: " + hd.getTongTienChuaGiam(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph giamGia = new Paragraph("Giam: " + (hd.getTongTienChuaGiam() - hd.getTongTien()), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));
            Paragraph kq = new Paragraph("Thành tien: " + hd.getTongTien(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, new CMYKColor(0, 0, 0, 255)));

            tongtien.setAlignment(Element.ALIGN_RIGHT);
            giamGia.setAlignment(Element.ALIGN_RIGHT);
            kq.setAlignment(Element.ALIGN_RIGHT);

            doc.add(tongtien);
            doc.add(giamGia);
            doc.add(kq);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChitietHoadonView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ChitietHoadonView.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }//GEN-LAST:event_btnInActionPerformed

    private void txtMHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMHDActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChitietHoadonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChitietHoadonView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboLonhap;
    private javax.swing.JComboBox<String> comboThuoc;
    private javax.swing.JTable dsCTHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinSoluong;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtDonvi;
    private javax.swing.JTextField txtMHD;
    // End of variables declaration//GEN-END:variables
}
