package Views;

import Controllers.LoaithuocController;
import Models.LoaiThuoc;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class LoaithuocView extends javax.swing.JPanel {

    ArrayList<LoaiThuoc> dsLoaithuoc;

    public LoaithuocView() {
        initComponents();
        //this.setLocationRelativeTo(null);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachLoaiThuoc.setDefaultRenderer(String.class, centerRenderer);
         for (int i = 0; i < tableDanhSachLoaiThuoc.getColumnCount(); i++) {
    tableDanhSachLoaiThuoc.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
}
        ((DefaultTableCellRenderer) tableDanhSachLoaiThuoc.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachLoaiThuoc.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        tableDanhSachLoaiThuoc.getTableHeader().setOpaque(false);
        tableDanhSachLoaiThuoc.getTableHeader().setBackground(Color.YELLOW);
        tableDanhSachLoaiThuoc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        if (!DangnhapView.quyenLogin.getChitietQuyen().contains("qlLoaiThuoc")) {
            btnThem.setEnabled(false);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
            btnThemFile.setEnabled(false);
            btnXuatFile.setEnabled(false);
        }

        ShowData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongTinLoaiThuoc = new javax.swing.JPanel();
        labelMaLoaiThuoc = new javax.swing.JLabel();
        labelTenLoaiThuoc = new javax.swing.JLabel();
        txtMaLoaiThuoc = new javax.swing.JTextField();
        txtTenLoaiThuoc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        txtMoTa = new javax.swing.JTextField();
        labelMota = new javax.swing.JLabel();
        panelDanhsachLoaiThuoc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhSachLoaiThuoc = new javax.swing.JTable();
        btnThemFile = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        panelThongTinLoaiThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin loại thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        labelMaLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMaLoaiThuoc.setText("Mã loại thuốc");

        labelTenLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTenLoaiThuoc.setText("Tên loại thuốc");

        txtMaLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtTenLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_database_restore_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_30px_1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 0, 0));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(0, 255, 0));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        labelMota.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMota.setText("Mô tả:");

        javax.swing.GroupLayout panelThongTinLoaiThuocLayout = new javax.swing.GroupLayout(panelThongTinLoaiThuoc);
        panelThongTinLoaiThuoc.setLayout(panelThongTinLoaiThuocLayout);
        panelThongTinLoaiThuocLayout.setHorizontalGroup(
            panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnThem)
                        .addGap(46, 46, 46)
                        .addComponent(btnHuy)
                        .addGap(32, 32, 32)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa))
                    .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                        .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMaLoaiThuoc)
                            .addComponent(labelTenLoaiThuoc)
                            .addComponent(labelMota))
                        .addGap(40, 40, 40)
                        .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(txtMaLoaiThuoc)
                            .addComponent(txtTenLoaiThuoc))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelThongTinLoaiThuocLayout.setVerticalGroup(
            panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaLoaiThuoc)
                    .addComponent(txtMaLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTenLoaiThuoc)
                    .addComponent(txtTenLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMota))
                .addGap(30, 30, 30)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuy)
                    .addComponent(btnLuu)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDanhsachLoaiThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách loại thuốc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(51, 51, 255))); // NOI18N
        panelDanhsachLoaiThuoc.setForeground(new java.awt.Color(51, 51, 255));
        panelDanhsachLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        tableDanhSachLoaiThuoc.setBackground(new java.awt.Color(102, 255, 255));
        tableDanhSachLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableDanhSachLoaiThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại thuốc", "Tên loại thuốc", "Mô tả"
            }
        ));
        tableDanhSachLoaiThuoc.setRowHeight(30);
        tableDanhSachLoaiThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachLoaiThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDanhSachLoaiThuoc);

        btnThemFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_ms_excel_30px.png"))); // NOI18N
        btnThemFile.setText("Thêm từ file");
        btnThemFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemFileActionPerformed(evt);
            }
        });

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_downloads_30px.png"))); // NOI18N
        btnXuatFile.setText("Xuất file");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_cancel_30px_1.png"))); // NOI18N
        btnThoat.setText("Thoát");

        javax.swing.GroupLayout panelDanhsachLoaiThuocLayout = new javax.swing.GroupLayout(panelDanhsachLoaiThuoc);
        panelDanhsachLoaiThuoc.setLayout(panelDanhsachLoaiThuocLayout);
        panelDanhsachLoaiThuocLayout.setHorizontalGroup(
            panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhsachLoaiThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemFile)
                .addGap(36, 36, 36)
                .addComponent(btnXuatFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(33, 33, 33))
            .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhsachLoaiThuocLayout.createSequentialGroup()
                    .addContainerGap(48, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelDanhsachLoaiThuocLayout.setVerticalGroup(
            panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhsachLoaiThuocLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemFile)
                    .addComponent(btnXuatFile)
                    .addComponent(btnThoat))
                .addGap(53, 53, 53))
            .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDanhsachLoaiThuocLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Thông tin về loại thuốc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDanhsachLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelThongTinLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(panelThongTinLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelDanhsachLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

       String maLoaiThuoc = String.valueOf(getMaLoaiThuocMoi());
txtMaLoaiThuoc.setText(maLoaiThuoc); 
btnLuu.setEnabled(true);
 btnHuy.setEnabled(true);
 txtMaLoaiThuoc.setEditable(false);
 btnThem.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc = Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsLoaithuoc.size(); i++) {
            if (dsLoaithuoc.get(i).getMaLoaiThuoc() == selectedMaLoaiThuoc) {
                selected = i;
            }
        }
        String maLoaiThuocString=txtMaLoaiThuoc.getText();
        String tenLoaiThuoc=txtTenLoaiThuoc.getText();
        String mota=txtMoTa.getText();
        if(maLoaiThuocString.equals("")||tenLoaiThuoc.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng không bỏ trống các trường dữ liệu","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        int maLoaiThuoc;
        try {
            maLoaiThuoc = Integer.parseInt(maLoaiThuocString);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng mã số Loại thuốc", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LoaiThuoc loaiThuocMoi=new LoaiThuoc(maLoaiThuoc,tenLoaiThuoc,mota);
        int maLoaiThuocCu=(dsLoaithuoc.get(selected).getMaLoaiThuoc());

        try {
            LoaithuocController.capnhatLoaiThuoc(loaiThuocMoi, maLoaiThuocCu);
            JOptionPane.showMessageDialog(this, "Cập nhật loại thuốc" + tenLoaiThuoc + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Lỗi, không cập nhật được loại thuốc " + tenLoaiThuoc + " !!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        }
        ShowData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc = Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsLoaithuoc.size(); i++) {
            if (dsLoaithuoc.get(i).getMaLoaiThuoc() == selectedMaLoaiThuoc) {
                selected = i;
            }
        }
        int maLoaiThuoc = dsLoaithuoc.get(selected).getMaLoaiThuoc();
        try {
            LoaithuocController.xoaLoaiThuoc(maLoaiThuoc);
            JOptionPane.showMessageDialog(this, "Xóa loại thuốc" + dsLoaithuoc.get(selected).getTenLoaiThuoc() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa loại thuốc" + dsLoaithuoc.get(selected).getTenLoaiThuoc() + " không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ShowData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableDanhSachLoaiThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachLoaiThuocMouseClicked
        // TODO add your handling code here:
        int selectedrow = tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc = Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsLoaithuoc.size(); i++) {
            if (dsLoaithuoc.get(i).getMaLoaiThuoc() == selectedMaLoaiThuoc) {
                selected = i;
            }
        }
        if(selected>=0)
        {
            txtMaLoaiThuoc.setText(String.valueOf(dsLoaithuoc.get(selected).getMaLoaiThuoc()));
            txtTenLoaiThuoc.setText(dsLoaithuoc.get(selected).getTenLoaiThuoc());
            txtMoTa.setText(dsLoaithuoc.get(selected).getMota());

        }
        txtMaLoaiThuoc.setEnabled(false);
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_tableDanhSachLoaiThuocMouseClicked

    private void btnThemFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemFileActionPerformed
        // TODO add your handling code here:
        
        ShowData();
    }//GEN-LAST:event_btnThemFileActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        
        String maLoaiThuocString=txtMaLoaiThuoc.getText();

        String tenLoaiThuoc=txtTenLoaiThuoc.getText();
        String mota=txtMoTa.getText();
        if(maLoaiThuocString.equals("")||tenLoaiThuoc.equals("")||txtMoTa.equals(null)||txtMoTa.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng không bỏ trống các trường dữ liệu","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        int maLoaiThuoc;
        try {
            maLoaiThuoc=Integer.parseInt(maLoaiThuocString);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lỗi định dạng số","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        LoaiThuoc loaiThuocMoi=new LoaiThuoc(maLoaiThuoc,tenLoaiThuoc, mota);
        try {
            LoaithuocController.themLoaiThuoc(loaiThuocMoi);
            JOptionPane.showMessageDialog(this,"Thêm loại thuốc "+tenLoaiThuoc+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Lỗi, không thêm được loại thuốc "+tenLoaiThuoc+" !!!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

        }
        ShowData();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
         int input = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn hủy hay không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            if (input == 0) {
            txtMaLoaiThuoc.setText("");
            txtTenLoaiThuoc.setText("");
            txtMoTa.setText("");
                     
            btnHuy.setEnabled(false);
            btnLuu.setEnabled(false);
            btnSua.setEnabled(false);
            btnThem.setEnabled(true);
            btnXoa.setEnabled(false);
            tableDanhSachLoaiThuoc.getSelectionModel().clearSelection();

        }
        }
    }//GEN-LAST:event_btnHuyActionPerformed
    public void ShowData()
    {
        DefaultTableModel tblModel=(DefaultTableModel) tableDanhSachLoaiThuoc.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
       dsLoaithuoc=LoaithuocController.getDanhSachLoaiThuoc();
        if(!dsLoaithuoc.isEmpty()){
                dsLoaithuoc.forEach((loaiThuoc)->{
                if(!loaiThuoc.isDaXoa())
                tblModel.addRow(new Object[]{loaiThuoc.getMaLoaiThuoc(),loaiThuoc.getTenLoaiThuoc(),loaiThuoc.getMota()});
                });
        }
        else
        {
          JOptionPane.showMessageDialog(this,"Danh sách loại thuốc rỗng","Thông báo",JOptionPane.INFORMATION_MESSAGE);

        }
         btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        txtMaLoaiThuoc.setEditable(false);
        btnThem.setEnabled(true);
    }
    public int getMaLoaiThuocMoi()
    {
        int maThuocMoi=0;
        for(LoaiThuoc loaiThuoc:dsLoaithuoc)
        {
            if(loaiThuoc.getMaLoaiThuoc()>maThuocMoi)
            {
                maThuocMoi=loaiThuoc.getMaLoaiThuoc();
            }
        }
        return maThuocMoi+1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemFile;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMaLoaiThuoc;
    private javax.swing.JLabel labelMota;
    private javax.swing.JLabel labelTenLoaiThuoc;
    private javax.swing.JPanel panelDanhsachLoaiThuoc;
    private javax.swing.JPanel panelThongTinLoaiThuoc;
    private javax.swing.JTable tableDanhSachLoaiThuoc;
    private javax.swing.JTextField txtMaLoaiThuoc;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenLoaiThuoc;
    // End of variables declaration//GEN-END:variables
}
