/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.LoaiThuocController;
import Models.LoaiThuoc;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HauPC
 */
public class LoaiThuocView extends javax.swing.JPanel {

    /**
     * Creates new form LoaiThuocView
     */
      ArrayList<LoaiThuoc> dsLoaiThuoc;
    public LoaiThuocView() {
        initComponents();
         //this.setLocationRelativeTo(null);
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongTinLoaiThuoc = new javax.swing.JPanel();
        labelMaLoaiThuoc = new javax.swing.JLabel();
        labelTenLoaiThuoc = new javax.swing.JLabel();
        txtMaLoaiThuoc = new javax.swing.JTextField();
        txtTenLoaiThuoc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        panelDanhsachLoaiThuoc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhSachLoaiThuoc = new javax.swing.JTable();
        btnThemFile = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        panelThongTinLoaiThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin loại thuốc"));

        labelMaLoaiThuoc.setText("Mã loại thuốc");

        labelTenLoaiThuoc.setText("Tên loại thuốc");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinLoaiThuocLayout = new javax.swing.GroupLayout(panelThongTinLoaiThuoc);
        panelThongTinLoaiThuoc.setLayout(panelThongTinLoaiThuocLayout);
        panelThongTinLoaiThuocLayout.setHorizontalGroup(
            panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaLoaiThuoc)
                    .addComponent(labelTenLoaiThuoc))
                .addGap(40, 40, 40)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                        .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtMaLoaiThuoc))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(44, 44, 44)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelThongTinLoaiThuocLayout.setVerticalGroup(
            panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLoaiThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaLoaiThuoc)
                    .addComponent(txtMaLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTenLoaiThuoc)
                    .addComponent(txtTenLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua)
                        .addComponent(btnThem))
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDanhsachLoaiThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách loại thuốc"));

        tableDanhSachLoaiThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại thuốc", "Tên loại thuốc"
            }
        ));
        tableDanhSachLoaiThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachLoaiThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDanhSachLoaiThuoc);

        btnThemFile.setText("Thêm từ file");
        btnThemFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemFileActionPerformed(evt);
            }
        });

        btnXuatFile.setText("Xuất file");

        btnThoat.setText("Thoát");

        javax.swing.GroupLayout panelDanhsachLoaiThuocLayout = new javax.swing.GroupLayout(panelDanhsachLoaiThuoc);
        panelDanhsachLoaiThuoc.setLayout(panelDanhsachLoaiThuocLayout);
        panelDanhsachLoaiThuocLayout.setHorizontalGroup(
            panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhsachLoaiThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemFile)
                .addGap(38, 38, 38)
                .addComponent(btnXuatFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(40, 40, 40))
            .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhsachLoaiThuocLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelDanhsachLoaiThuocLayout.setVerticalGroup(
            panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhsachLoaiThuocLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemFile)
                    .addComponent(btnXuatFile)
                    .addComponent(btnThoat))
                .addGap(105, 105, 105))
            .addGroup(panelDanhsachLoaiThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhsachLoaiThuocLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDanhsachLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelThongTinLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelThongTinLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDanhsachLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maLoaiThuocString=txtMaLoaiThuoc.getText();

        String tenLoaiThuoc=txtTenLoaiThuoc.getText();
        if(maLoaiThuocString.equals("")||tenLoaiThuoc.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng không bỏ trống các trường dữ liệu","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        int maLoaiThuoc;
        try {
            maLoaiThuoc=Integer.parseInt(maLoaiThuocString);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lỗi định dạng số","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        LoaiThuoc loaiThuocMoi=new LoaiThuoc(maLoaiThuoc,tenLoaiThuoc);
        try {
            LoaiThuocController.themLoaiThuoc(loaiThuocMoi);
            JOptionPane.showMessageDialog(this,"Thêm loại thuốc"+tenLoaiThuoc+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Lỗi, không thêm được loại thuốc "+tenLoaiThuoc+" !!!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

        }
        ShowData();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedrow=tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc=Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsLoaiThuoc.size();i++)
        {
            if(dsLoaiThuoc.get(i).getMaLoaiThuoc()==selectedMaLoaiThuoc)
            {
                selected=i;
            }
        }
        String maLoaiThuocString=txtMaLoaiThuoc.getText();
        String tenLoaiThuoc=txtTenLoaiThuoc.getText();
        if(maLoaiThuocString.equals("")||tenLoaiThuoc.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng không bỏ trống các trường dữ liệu","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        int maLoaiThuoc;
        try {
            maLoaiThuoc=Integer.parseInt(maLoaiThuocString);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lỗi định dạng mã số Loại thuốc","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        LoaiThuoc loaiThuocMoi=new LoaiThuoc(maLoaiThuoc,tenLoaiThuoc);
        int maLoaiThuocCu=(dsLoaiThuoc.get(selected).getMaLoaiThuoc());
        try {
            LoaiThuocController.capnhatLoaiThuoc(loaiThuocMoi,maLoaiThuocCu);
            JOptionPane.showMessageDialog(this,"Cập nhật loại thuốc"+tenLoaiThuoc+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Lỗi, không cập nhật được loại thuốc "+tenLoaiThuoc+" !!!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

        }
        ShowData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedrow=tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc=Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsLoaiThuoc.size();i++)
        {
            if(dsLoaiThuoc.get(i).getMaLoaiThuoc()==selectedMaLoaiThuoc)
            {
                selected=i;
            }
        }
        int maLoaiThuoc=dsLoaiThuoc.get(selected).getMaLoaiThuoc();
        try {
            LoaiThuocController.xoaLoaiThuoc(maLoaiThuoc);
            JOptionPane.showMessageDialog(this,"Xóa loại thuốc"+dsLoaiThuoc.get(selected).getTenLoaiThuoc()+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Xóa loại thuốc"+dsLoaiThuoc.get(selected).getTenLoaiThuoc()+" không thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ShowData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableDanhSachLoaiThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachLoaiThuocMouseClicked
        // TODO add your handling code here:
        int selectedrow=tableDanhSachLoaiThuoc.getSelectedRow();
        int selectedMaLoaiThuoc=Integer.parseInt(tableDanhSachLoaiThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsLoaiThuoc.size();i++)
        {
            if(dsLoaiThuoc.get(i).getMaLoaiThuoc()==selectedMaLoaiThuoc)
            {
                selected=i;
            }
        }
        if(selected>=0)
        {
            txtMaLoaiThuoc.setText(String.valueOf(dsLoaiThuoc.get(selected).getMaLoaiThuoc()));
            txtTenLoaiThuoc.setText(dsLoaiThuoc.get(selected).getTenLoaiThuoc());
        }
    }//GEN-LAST:event_tableDanhSachLoaiThuocMouseClicked

    private void btnThemFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemFileActionPerformed
    public void ShowData()
    {
        DefaultTableModel tblModel=(DefaultTableModel) tableDanhSachLoaiThuoc.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
       dsLoaiThuoc=LoaiThuocController.getDanhSachLoaiThuoc();
        if(!dsLoaiThuoc.isEmpty()){
                dsLoaiThuoc.forEach((nhacungcap1)->{
                if(!nhacungcap1.isDaXoa())
                tblModel.addRow(new Object[]{nhacungcap1.getMaLoaiThuoc(),nhacungcap1.getTenLoaiThuoc()});
                });
        }
        else
        {
          JOptionPane.showMessageDialog(this,"Danh sách loại thuốc rỗng","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemFile;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMaLoaiThuoc;
    private javax.swing.JLabel labelTenLoaiThuoc;
    private javax.swing.JPanel panelDanhsachLoaiThuoc;
    private javax.swing.JPanel panelThongTinLoaiThuoc;
    private javax.swing.JTable tableDanhSachLoaiThuoc;
    private javax.swing.JTextField txtMaLoaiThuoc;
    private javax.swing.JTextField txtTenLoaiThuoc;
    // End of variables declaration//GEN-END:variables
}
