package Views;

import Components.AutoCompletion;
import Components.ReadExcelNhacungcap;
import Components.WriteExcelNhacungcap;
import Controllers.HuyenController;
import Controllers.NhacungcapController;
import Controllers.TinhController;
import Controllers.XaController;
import Models.Huyen;
import Models.Nhacungcap;
import Models.Tinh;
import Models.Xa;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.*;

import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class NhacungcapView extends javax.swing.JPanel {

    ArrayList<Nhacungcap> dsNhacungcap;

    public NhacungcapView() {
        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableNhacungcap.setDefaultRenderer(String.class, centerRenderer);
         for (int i = 0; i < tableNhacungcap.getColumnCount(); i++) {
    tableNhacungcap.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
}
        ((DefaultTableCellRenderer) tableNhacungcap.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tableNhacungcap.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        tableNhacungcap.getTableHeader().setOpaque(false);
        tableNhacungcap.getTableHeader().setBackground(Color.YELLOW);
        if (!DangnhapView.quyenLogin.getChitietQuyen().contains("qlNCC")) {
            btnThem.setEnabled(false);
            btnThemfile.setEnabled(false);
            btnXuatFile.setEnabled(false);
        }
        showXa();
        ShowData();
        showTinh();
        showHuyen();
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        txtMaNhacungcap.setEditable(false);
        ShowSearchComboBox();

        //txtMaNhacungcap.addKeyListener(new KeyCustom());
    }

    public String getSelectedRow(int col) {
        int i = tableNhacungcap.getSelectedRow();
        if (i >= 0) {
            int realI = tableNhacungcap.convertRowIndexToModel(i);
            return tableNhacungcap.getModel().getValueAt(realI, col).toString();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhacungcap = new javax.swing.JTable();
        panelThongtinNhacungcap = new javax.swing.JPanel();
        labelTennhacungcap = new javax.swing.JLabel();
        labelXa = new javax.swing.JLabel();
        lableSdt = new javax.swing.JLabel();
        labelFax = new javax.swing.JLabel();
        labelManhacungcap = new javax.swing.JLabel();
        txtMaNhacungcap = new javax.swing.JTextField();
        txtTenNhacungcap = new javax.swing.JTextField();
        txtSodienthoai = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtXa = new javax.swing.JComboBox<>();
        txtHuyen = new javax.swing.JComboBox<>();
        labelHuyen = new javax.swing.JLabel();
        txtTinh = new javax.swing.JComboBox<>();
        labelTinh = new javax.swing.JLabel();
        btnXuatFile = new javax.swing.JButton();
        btnThemfile = new javax.swing.JButton();
        labelTimKiem = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        txtSearchBox = new com.raven.chart.TextFieldSuggestion();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        tableNhacungcap.setBackground(new java.awt.Color(204, 255, 255));
        tableNhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableNhacungcap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Fax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNhacungcap.setRowHeight(30);
        tableNhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhacungcapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhacungcap);
        tableNhacungcap.getAccessibleContext().setAccessibleDescription("");

        panelThongtinNhacungcap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 22), new java.awt.Color(0, 0, 204))); // NOI18N
        panelThongtinNhacungcap.setPreferredSize(new java.awt.Dimension(1037, 387));

        labelTennhacungcap.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTennhacungcap.setText("Tên nhà cung cấp: ");

        labelXa.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelXa.setText("Xã:");

        lableSdt.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lableSdt.setText("Số điện thoại:");

        labelFax.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelFax.setText("Fax:");

        labelManhacungcap.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelManhacungcap.setText("Mã nhà cung cấp:");

        txtMaNhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaNhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhacungcapActionPerformed(evt);
            }
        });
        txtMaNhacungcap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaNhacungcapKeyPressed(evt);
            }
        });

        txtTenNhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenNhacungcap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenNhacungcapKeyPressed(evt);
            }
        });

        txtSodienthoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSodienthoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSodienthoaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSodienthoaiKeyTyped(evt);
            }
        });

        txtfax.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtfax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaxActionPerformed(evt);
            }
        });
        txtfax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfaxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfaxKeyTyped(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-save-30.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_database_restore_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_forever_30px_1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeLoginIcon.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtXa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtXa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXaActionPerformed(evt);
            }
        });

        txtHuyen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtHuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHuyenActionPerformed(evt);
            }
        });

        labelHuyen.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelHuyen.setText("Huyện:");

        txtTinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhActionPerformed(evt);
            }
        });

        labelTinh.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTinh.setText("Tỉnh:");

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_downloads_30px.png"))); // NOI18N
        btnXuatFile.setText("Xuất file");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        btnThemfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_ms_excel_30px.png"))); // NOI18N
        btnThemfile.setText("Thêm từ file");
        btnThemfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongtinNhacungcapLayout = new javax.swing.GroupLayout(panelThongtinNhacungcap);
        panelThongtinNhacungcap.setLayout(panelThongtinNhacungcapLayout);
        panelThongtinNhacungcapLayout.setHorizontalGroup(
            panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addGap(653, 653, 653)
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelXa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFax, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelManhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTennhacungcap))
                            .addComponent(labelTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtXa, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnHuy)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLuu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThemfile)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXuatFile))
                                    .addComponent(txtHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 196, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelThongtinNhacungcapLayout.setVerticalGroup(
            panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongtinNhacungcapLayout.createSequentialGroup()
                            .addComponent(labelXa)
                            .addGap(81, 81, 81))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongtinNhacungcapLayout.createSequentialGroup()
                            .addComponent(lableSdt)
                            .addGap(15, 15, 15)
                            .addComponent(labelFax)))
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelManhacungcap))
                        .addGap(15, 15, 15)
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTennhacungcap))
                        .addGap(15, 15, 15)
                        .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTinh)))
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addComponent(txtXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelHuyen))
                    .addGroup(panelThongtinNhacungcapLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(panelThongtinNhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(btnXuatFile)
                    .addComponent(btnThemfile))
                .addGap(81, 81, 81))
        );

        labelTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTimKiem.setForeground(new java.awt.Color(255, 0, 0));
        labelTimKiem.setText("Thông tin tìm kiếm");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelThongtinNhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(labelTimKiem)
                .addGap(18, 18, 18)
                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTimKiem)
                            .addComponent(btnTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelThongtinNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableNhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhacungcapMouseClicked
        // TODO add your handling code here:
        //chon dong trong bang nha cung cap se hien thi du lieu len text field
        int selectedrow = tableNhacungcap.getSelectedRow();
        int selectedMaNhacungcap = Integer.parseInt(tableNhacungcap.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsNhacungcap.size(); i++) {
            if (dsNhacungcap.get(i).getMaNhacungcap() == selectedMaNhacungcap) {
                selected = i;
            }
        }
        if (selected >= 0) {
            txtMaNhacungcap.setText(String.valueOf(dsNhacungcap.get(selected).getMaNhacungcap()));
            txtTenNhacungcap.setText(dsNhacungcap.get(selected).getTenNhacungcap());
            DefaultComboBoxModel xaComboBoxModel = (DefaultComboBoxModel) txtXa.getModel();

            for (int i = 0; i < xaComboBoxModel.getSize(); i++) {
                Xa xa = (Xa) xaComboBoxModel.getElementAt(i);
                if (xa.getMaXa() == (dsNhacungcap.get(selected).getXa()).getMaXa()) {
                    txtXa.setSelectedIndex(i);
                    break;
                }
            }
            txtSodienthoai.setText(String.valueOf(dsNhacungcap.get(selected).getSoDienthoai()));
            txtfax.setText(String.valueOf(dsNhacungcap.get(selected).getFax()));
        }
        txtMaNhacungcap.setEnabled(false);
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnHuy.setEnabled(true);


    }//GEN-LAST:event_tableNhacungcapMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyChar());
        if (evt.isControlDown() && evt.getKeyCode() == 65) {
            System.out.println("Select All");
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        System.out.println(evt.getKeyChar());
        if (evt.isControlDown() && evt.getKeyCode() == 65) {
            System.out.println("Select All");
        }
    }//GEN-LAST:event_formKeyReleased

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        //Tham khảo tại https://stackhowto.com/export-data-from-jtable-to-excel-in-java/
        WriteExcelNhacungcap writeExcelNhacungcap = new WriteExcelNhacungcap();
        final List<Nhacungcap> nhacungcaps = NhacungcapController.getDanhSachNhacungcap();
        JFileChooser fchoose = new JFileChooser();
        int option = fchoose.showOpenDialog(fchoose);
        if (option == JFileChooser.APPROVE_OPTION) {
            String name = fchoose.getSelectedFile().getName();
            String path = fchoose.getSelectedFile().getParentFile().getPath();
            String file = path + "\\" + name + ".xlsx";
            final String excelFilePath = file;
            try {
                writeExcelNhacungcap.writeExcel(nhacungcaps, excelFilePath);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnThemfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("File excel", "xlsx", "xls", "csv");
        fileChooser.setFileFilter(filefilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Open");

        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.exists()) {
                int result = JOptionPane.showConfirmDialog(this, "The file " + file.getName() + " không tồn tại", "Thông báo", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

            } else {
                try {

                    ReadExcelNhacungcap c = new ReadExcelNhacungcap();
                    ArrayList<Nhacungcap> dsnhaNhacungcaps = c.readExcel(file.getAbsolutePath());
                    dsnhaNhacungcaps.forEach(Nhacungcap -> {
                        try {
                            NhacungcapController.themNhacungcap(Nhacungcap);
                        } catch (Exception ex) {
                            Logger.getLogger(NhacungcapView.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                    JOptionPane.showMessageDialog(this, "Thêm danh sách nhà cung cấp từ file: " + file.getAbsolutePath() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ShowData();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }//GEN-LAST:event_btnThemfileActionPerformed

    private void txtTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhActionPerformed
        // TODO add your handling code here:
        Tinh tinhSelected = (Tinh) txtTinh.getSelectedItem();
        showHuyen(tinhSelected.getTenTinh());
    }//GEN-LAST:event_txtTinhActionPerformed

    private void txtHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHuyenActionPerformed
        // TODO add your handling code here:
        Huyen huyenSelected = (Huyen) txtHuyen.getSelectedItem();
        if (huyenSelected != null) {
             showXa(huyenSelected.getTenHuyen());
        } else {
            DefaultComboBoxModel xaBoxModel = (DefaultComboBoxModel) txtXa.getModel();
            xaBoxModel.removeAllElements();
        }
    }//GEN-LAST:event_txtHuyenActionPerformed

    private void txtXaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
            "Bạn có chắc muốn hủy hay không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            if (input == 0) {
                txtMaNhacungcap.setText("");
                txtTenNhacungcap.setText("");
                txtSodienthoai.setText("");
                txtfax.setText("");

                btnHuy.setEnabled(false);
                btnLuu.setEnabled(false);
                btnSua.setEnabled(false);
                btnThem.setEnabled(true);
                tableNhacungcap.getSelectionModel().clearSelection();

            }
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableNhacungcap.getSelectedRow();
        int selectedMaNhacungcap = Integer.parseInt(tableNhacungcap.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsNhacungcap.size(); i++) {
            if (dsNhacungcap.get(i).getMaNhacungcap() == selectedMaNhacungcap) {
                selected = i;
            }
        }
        int maNhacungcap = dsNhacungcap.get(selected).getMaNhacungcap();
        try {
            NhacungcapController.xoaNhacungcap(maNhacungcap);
            JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp" + dsNhacungcap.get(selected).getTenNhacungcap() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp" + dsNhacungcap.get(selected).getTenNhacungcap() + " không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ShowData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableNhacungcap.getSelectedRow();
        int selectedMaNhacungcap = Integer.parseInt(tableNhacungcap.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsNhacungcap.size(); i++) {
            if (dsNhacungcap.get(i).getMaNhacungcap() == selectedMaNhacungcap) {
                selected = i;
            }
        }
        String maNhacungcapString = txtMaNhacungcap.getText();
        int maNhacungcap = Integer.parseInt(maNhacungcapString);
        String tenNhacungcap = txtTenNhacungcap.getText();
        String soDienThoai = txtSodienthoai.getText();
        Xa xa = (Xa) txtXa.getSelectedItem();
        String fax = txtfax.getText();
        if (maNhacungcapString.equals("") || tenNhacungcap.equals("") || soDienThoai.equals("") || xa.equals("") || fax.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng không được bỏ trống các ô thông tin!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        Nhacungcap nhacungcap = new Nhacungcap(maNhacungcap, tenNhacungcap, xa, soDienThoai, fax);
        int maNhacungcapCu = (dsNhacungcap.get(selected).getMaNhacungcap());
        try {
            NhacungcapController.capnhatNhacungcap(nhacungcap, maNhacungcapCu);
            JOptionPane.showMessageDialog(this, "Cap nhat nhà cung cấp" + nhacungcap.getTenNhacungcap() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cập nhật nhà cung cấp không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maNhacungcapString = txtMaNhacungcap.getText();
        int maNhacungcap = -1;
        try {
            maNhacungcap = Integer.parseInt(maNhacungcapString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String tenNhacungcap = txtTenNhacungcap.getText();
        String soDienThoai = txtSodienthoai.getText();
        Xa xa = (Xa) txtXa.getSelectedItem();
        String fax = txtfax.getText();
        String regex ="(84|0[3|5|7|8|9])+([0-9]{8})\\b"; 
//        String regex ="(84|0[3|5|7|8|9])+([0-9]{8})\\b";
        if (maNhacungcapString.equals("") || maNhacungcapString.equals(null) || tenNhacungcap.equals("") || tenNhacungcap.equals(null) || soDienThoai.equals("") || soDienThoai.equals(null) || xa.equals("") || fax.equals("") || fax.equals(null) || xa.equals(null)) {
            JOptionPane.showMessageDialog(this, "Vui lòng không được bỏ trống các ô thông tin hoặc số điện thoại không đúng !!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!soDienThoai.matches(regex))
        {
             JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ !!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Nhacungcap nhacungcap = new Nhacungcap(maNhacungcap, tenNhacungcap, xa, soDienThoai, fax);
        try {
            NhacungcapController.themNhacungcap(nhacungcap);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp " + nhacungcap.getTenNhacungcap() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        ShowData();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtMaNhacungcap.setText(String.valueOf(getMaNhacungcapMoi()));
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
        btnThem.setEnabled(false);
        txtMaNhacungcap.setEnabled(true);

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtfaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtfaxKeyTyped

    private void txtfaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnThem.requestFocus();
        }
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_S) {
            btnThem.doClick();
        }
    }//GEN-LAST:event_txtfaxKeyPressed

    private void txtfaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaxActionPerformed

    private void txtSodienthoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodienthoaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtSodienthoaiKeyTyped

    private void txtSodienthoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodienthoaiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfax.requestFocus();
        }
    }//GEN-LAST:event_txtSodienthoaiKeyPressed

    private void txtTenNhacungcapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNhacungcapKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtXa.requestFocus();
        }
    }//GEN-LAST:event_txtTenNhacungcapKeyPressed

    private void txtMaNhacungcapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNhacungcapKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTenNhacungcap.requestFocus();
        }
    }//GEN-LAST:event_txtMaNhacungcapKeyPressed

    private void txtMaNhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhacungcapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhacungcapActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        //Tìm kiếm nhà cung cấp.
        String searchText = txtSearchBox.getText();
        if(searchText.equals("")||searchText.equals(null))
        {
            ShowData();
        }
        else
        {
            DefaultTableModel tblModel = (DefaultTableModel) tableNhacungcap.getModel();
            tblModel.getDataVector().removeAllElements();
            tblModel.fireTableDataChanged();
            if(dsNhacungcap.equals(null))
            {
                ShowData();
            }
            if (!dsNhacungcap.isEmpty()) {
                dsNhacungcap.forEach((nhacungcap1) -> {
                    if (!nhacungcap1.isDaXoa()&&(String.valueOf(nhacungcap1.getMaNhacungcap()).contains(searchText))||nhacungcap1.getTenNhacungcap().contains(searchText)||nhacungcap1.getSoDienthoai().contains(searchText)||nhacungcap1.getFax().contains(searchText)||nhacungcap1.getXa().getDiaChi().contains(searchText)) {
                        tblModel.addRow(new Object[]{nhacungcap1.getMaNhacungcap(), nhacungcap1.getTenNhacungcap(), nhacungcap1.getXa().getDiaChi(), nhacungcap1.getSoDienthoai(), nhacungcap1.getFax()});
                    }
                });
            } else {
                JOptionPane.showMessageDialog(this, "Danh sách nhà cung cấp rỗng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed
    public void ShowData() {
        DefaultTableModel tblModel = (DefaultTableModel) tableNhacungcap.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
        dsNhacungcap = NhacungcapController.getDanhSachNhacungcap();
        if (!dsNhacungcap.isEmpty()) {
            dsNhacungcap.forEach((nhacungcap1) -> {
                if (!nhacungcap1.isDaXoa()) {
                    tblModel.addRow(new Object[]{nhacungcap1.getMaNhacungcap(), nhacungcap1.getTenNhacungcap(), nhacungcap1.getXa().getDiaChi(), nhacungcap1.getSoDienthoai(), nhacungcap1.getFax()});
                }
            });
        } else {
            JOptionPane.showMessageDialog(this, "Danh sách nhà cung cấp rỗng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        }
        tableNhacungcap.setAutoCreateRowSorter(true);
        txtMaNhacungcap.setEnabled(false);
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnHuy.setEnabled(true);
    }

    public void ShowSearchComboBox() {
 Set<String> hash_Set = new HashSet<String>();
        dsNhacungcap.forEach(Nhacungcap -> {
           hash_Set.add(String.valueOf(Nhacungcap.getMaNhacungcap()));
            hash_Set.add(Nhacungcap.getTenNhacungcap());
             hash_Set.add(Nhacungcap.getSoDienthoai());
            hash_Set.add(Nhacungcap.getXa().getDiaChi());
             hash_Set.add(Nhacungcap.getFax());
        }
        );
        txtSearchBox.clearItemSuggestion();
        ArrayList<String> keywords = new ArrayList<String>();
        Iterator value = hash_Set.iterator();
         while (value.hasNext()) {
          txtSearchBox.addItemSuggestion((String) value.next());
        }
    }


    public void showTinh() {
        DefaultComboBoxModel tinhBoxModel = (DefaultComboBoxModel) txtTinh.getModel();
        tinhBoxModel.removeAllElements();
        TinhController tinhController = new TinhController();
        ArrayList<Tinh> dsTinh = tinhController.getDanhsachTinh();
        dsTinh.forEach(tinh -> {
            tinhBoxModel.addElement(tinh);
        });
    }

    public void showHuyen() {
        DefaultComboBoxModel huyenBoxModel = (DefaultComboBoxModel) txtHuyen.getModel();
        huyenBoxModel.removeAllElements();
        HuyenController huyenController = new HuyenController();
        ArrayList<Huyen> dsHuyen = huyenController.getDanhsachHuyen();
        dsHuyen.forEach(huyen -> {
            huyenBoxModel.addElement(huyen);
        });
    }
    public void showHuyen(String tenTinh){
        DefaultComboBoxModel huyenBoxModel=(DefaultComboBoxModel) txtHuyen.getModel();
      huyenBoxModel.removeAllElements();
      HuyenController huyenController=new HuyenController();
        ArrayList<Huyen> dsHuyen= huyenController.getDanhsachHuyenTheoTinh(tenTinh);
        dsHuyen.forEach(huyen->{
            huyenBoxModel.addElement(huyen);
        });      
    }

    public void showXa() {
        DefaultComboBoxModel xaBoxModel = (DefaultComboBoxModel) txtXa.getModel();
        xaBoxModel.removeAllElements();
        XaController xaController = new XaController();
        ArrayList<Xa> dsXa = xaController.getDanhsachXa();
        dsXa.forEach(xa -> {
            xaBoxModel.addElement(xa);
        });
    }
    public void showXa(String tenHuyen){
        DefaultComboBoxModel xaBoxModel=(DefaultComboBoxModel) txtXa.getModel();
      xaBoxModel.removeAllElements();
      XaController xaController=new XaController();
        ArrayList<Xa> dsXa= xaController.getDanhsachXaTheoHuyen(tenHuyen);
        dsXa.forEach(xa->{
            xaBoxModel.addElement(xa);
        });       
    }

    public int getMaNhacungcapMoi() {
        int maNhacungcapMoi = 0;
        if (!dsNhacungcap.isEmpty()) {
            for (Nhacungcap nhacungcap : dsNhacungcap) {
                if (nhacungcap.getMaNhacungcap() > maNhacungcapMoi) {
                    maNhacungcapMoi = nhacungcap.getMaNhacungcap();
                }
            }
        }
        return maNhacungcapMoi + 1;

    }

    class KeyCustom implements KeyListener {

        @Override
        public void keyTyped(KeyEvent e) {
            System.out.println(e.getKeyChar());
        }

        @Override
        public void keyPressed(KeyEvent e) {
            System.out.println(e.getKeyChar());
            if (e.isControlDown() && e.getKeyCode() == 65) {
                System.out.println("Select All");
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemfile;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFax;
    private javax.swing.JLabel labelHuyen;
    private javax.swing.JLabel labelManhacungcap;
    private javax.swing.JLabel labelTennhacungcap;
    private javax.swing.JLabel labelTimKiem;
    private javax.swing.JLabel labelTinh;
    private javax.swing.JLabel labelXa;
    private javax.swing.JLabel lableSdt;
    private javax.swing.JPanel panelThongtinNhacungcap;
    private javax.swing.JTable tableNhacungcap;
    private javax.swing.JComboBox<String> txtHuyen;
    private javax.swing.JTextField txtMaNhacungcap;
    private com.raven.chart.TextFieldSuggestion txtSearchBox;
    private javax.swing.JTextField txtSodienthoai;
    private javax.swing.JTextField txtTenNhacungcap;
    private javax.swing.JComboBox<String> txtTinh;
    private javax.swing.JComboBox<String> txtXa;
    private javax.swing.JTextField txtfax;
    // End of variables declaration//GEN-END:variables
}
