/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.BaoCaoController;
import com.raven.chart.ModelChart;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author HauPC
 */
public class ThongKeSoLuongDonBan extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeDonThuoc
     */
    public ThongKeSoLuongDonBan() {
        initComponents();
        showNam();
  chart.addLegend("Số lượng", new Color(160, 70, 170));
  int nam=(int) txtChonNam.getSelectedItem();
        initChart(nam);
            
    }
    public void initChart(int nam)
    {   
        chart.removeData();
         BaoCaoController baocao=new BaoCaoController();
        HashMap<Integer,Integer> soluongDonBan=new HashMap<>();
        soluongDonBan=baocao.getSoLuongDonThuoc(nam);
        System.out.println(soluongDonBan);
        chart.addData(new ModelChart("Tháng 1", new double[]{soluongDonBan.get(1)==null? 0:soluongDonBan.get(1)}));
        chart.addData(new ModelChart("Tháng 2", new double[]{soluongDonBan.get(2)==null? 0:soluongDonBan.get(2)}));
        chart.addData(new ModelChart("Tháng 3", new double[]{soluongDonBan.get(3)==null? 0:soluongDonBan.get(3)}));
        chart.addData(new ModelChart("Tháng 4", new double[]{soluongDonBan.get(4)==null? 0:soluongDonBan.get(4)}));
        chart.addData(new ModelChart("Tháng 5", new double[]{soluongDonBan.get(5)==null? 0:soluongDonBan.get(5)}));
        chart.addData(new ModelChart("Tháng 6", new double[]{soluongDonBan.get(6)==null? 0:soluongDonBan.get(6)}));
        chart.addData(new ModelChart("Tháng 7", new double[]{soluongDonBan.get(7)==null? 0:soluongDonBan.get(7)}));
        chart.addData(new ModelChart("Tháng 8", new double[]{soluongDonBan.get(8)==null? 0:soluongDonBan.get(8)}));
        chart.addData(new ModelChart("Tháng 9", new double[]{soluongDonBan.get(9)==null? 0:soluongDonBan.get(9)}));
        chart.addData(new ModelChart("Tháng 10", new double[]{soluongDonBan.get(10)==null? 0:soluongDonBan.get(10)}));
        chart.addData(new ModelChart("Tháng 11", new double[]{soluongDonBan.get(11)==null? 0:soluongDonBan.get(11)}));
        chart.addData(new ModelChart("Tháng 12", new double[]{soluongDonBan.get(12)==null? 0:soluongDonBan.get(12)}));

    }
    public void showNam()
    {
         DefaultComboBoxModel chonNamModel=(DefaultComboBoxModel) txtChonNam.getModel();
         BaoCaoController baoCaoController=new BaoCaoController();
      chonNamModel.removeAllElements();
        ArrayList<Integer> nams= baoCaoController.getNamHoaDon();
        nams.forEach(nam->{
            chonNamModel.addElement(nam);
        });        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtChonNam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chart = new com.raven.chart.ChartSL();
        jLabel3 = new javax.swing.JLabel();

        txtChonNam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtChonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChonNamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("Chọn Năm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Thống Kê Số Lượng Đơn Thuốc Được Bán Theo Năm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Báo cáo số lượng đơn hàng trong năm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1826, 1826, 1826)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74)
                        .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtChonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChonNamActionPerformed
        // TODO add your handling code here:
        if (txtChonNam.getSelectedItem() != null) {
            int nam = (int) txtChonNam.getSelectedItem();
            initChart(nam);
            chart.setVisible(false);
            chart.setVisible(true);
        }

    }//GEN-LAST:event_txtChonNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.ChartSL chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> txtChonNam;
    // End of variables declaration//GEN-END:variables
}
