/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.DonvitinhController;
import Controllers.ThuocController;
import Controllers.LoaiThuocController;
import javax.swing.DefaultListModel;
import Models.Donvitinh;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Controllers.ThuocController;
import Models.Thuoc;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import Components.SetImage;
import Controllers.NhacungcapController;
import Models.LoaiThuoc;
import Models.Nhacungcap;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author HauPC
 */
public class ThuocView extends javax.swing.JPanel {

    /**
     * Creates new form ThuocView
     */
     String hinhanh="";
     ArrayList<Thuoc> dsThuoc;
    public ThuocView() {
        initComponents();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachThuoc.setDefaultRenderer(String.class, centerRenderer);
        ((DefaultTableCellRenderer) tableDanhSachThuoc.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachThuoc.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        tableDanhSachThuoc.getTableHeader().setOpaque(false);
        tableDanhSachThuoc.getTableHeader().setBackground(Color.YELLOW);
         tableDanhSachThuoc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ShowData();
        showLoaiThuoc();
        showDonvitinh();
        showDonviQuydoi();
        showNhacungcap();
        showDotuoiThuoc();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThemThuoc = new javax.swing.JPanel();
        labelMaloaithuoc = new javax.swing.JLabel();
        txtLoaiThuoc = new javax.swing.JComboBox<>();
        labelTenThuoc = new javax.swing.JLabel();
        txtTenThuoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotaThuoc = new javax.swing.JTextArea();
        labelMota = new javax.swing.JLabel();
        txtnhacungcapThuoc = new javax.swing.JComboBox<>();
        labelNhacungcap = new javax.swing.JLabel();
        txtDonvitinhThuoc = new javax.swing.JComboBox<>();
        labelDonvitinhThuoc = new javax.swing.JLabel();
        btnChonHinhanhThuoc = new javax.swing.JButton();
        labelHinhThuoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDotuoiThuoc = new javax.swing.JList<>();
        labelDotuoiThuoc = new javax.swing.JLabel();
        giabanThuoc = new javax.swing.JTextField();
        labelGiabanThuoc = new javax.swing.JLabel();
        btnThemThuoc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelHinhanh = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaThuoc = new javax.swing.JTextField();
        txtDonviQuydoi = new javax.swing.JComboBox<>();
        labelDonviQuydoi = new javax.swing.JLabel();
        txtTiLeQuyDoi = new javax.swing.JTextField();
        labelTileQuyDoi = new javax.swing.JLabel();
        panelDanhSachThuoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDanhSachThuoc = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btnThemFile = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        thoatNhapThuoc = new javax.swing.JButton();

        panelThemThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin thuốc"));
        panelThemThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelThemThuocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelThemThuocKeyTyped(evt);
            }
        });

        labelMaloaithuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMaloaithuoc.setText("Mã loại thuốc");

        txtLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        labelTenThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTenThuoc.setText("Tên thuốc");

        txtTenThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtMotaThuoc.setColumns(5);
        txtMotaThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMotaThuoc.setRows(5);
        jScrollPane2.setViewportView(txtMotaThuoc);

        labelMota.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMota.setText("Mô tả");

        txtnhacungcapThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtnhacungcapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhacungcapThuocActionPerformed(evt);
            }
        });

        labelNhacungcap.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelNhacungcap.setText("Nhà cung cấp");

        txtDonvitinhThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDonvitinhThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonvitinhThuocActionPerformed(evt);
            }
        });

        labelDonvitinhThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDonvitinhThuoc.setText("Đơn vị tính");

        btnChonHinhanhThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnChonHinhanhThuoc.setText("Chọn hình ảnh");
        btnChonHinhanhThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhanhThuocActionPerformed(evt);
            }
        });

        labelHinhThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelHinhThuoc.setText("Hình ảnh");

        listDotuoiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(listDotuoiThuoc);

        labelDotuoiThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDotuoiThuoc.setText("Độ tuổi");

        giabanThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        giabanThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giabanThuocActionPerformed(evt);
            }
        });
        giabanThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                giabanThuocKeyTyped(evt);
            }
        });

        labelGiabanThuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelGiabanThuoc.setText("Giá bán");

        btnThemThuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThemThuoc.setText("Thêm thuốc");
        btnThemThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ảnh Thuốc"));

        labelHinhanh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelHinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_database_restore_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_30px_1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Mã thuốc");

        txtMaThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDonviQuydoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        labelDonviQuydoi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDonviQuydoi.setText("Đơn vị quy đổi");

        txtTiLeQuyDoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTiLeQuyDoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiLeQuyDoiKeyTyped(evt);
            }
        });

        labelTileQuyDoi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTileQuyDoi.setText("Tỉ lệ quy đổi");

        javax.swing.GroupLayout panelThemThuocLayout = new javax.swing.GroupLayout(panelThemThuoc);
        panelThemThuoc.setLayout(panelThemThuocLayout);
        panelThemThuocLayout.setHorizontalGroup(
            panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemThuocLayout.createSequentialGroup()
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelMota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtTenThuoc)
                            .addComponent(txtMaThuoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDotuoiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addComponent(labelDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelThemThuocLayout.createSequentialGroup()
                                    .addComponent(labelDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelThemThuocLayout.createSequentialGroup()
                                    .addComponent(labelTileQuyDoi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTiLeQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelThemThuocLayout.createSequentialGroup()
                                            .addComponent(btnThemThuoc)
                                            .addGap(106, 106, 106)
                                            .addComponent(btnSua))))))
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMaloaithuoc)
                                    .addComponent(labelNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelGiabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonHinhanhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnXoa))
                    .addComponent(giabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnhacungcapThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(294, 294, 294))
        );
        panelThemThuocLayout.setVerticalGroup(
            panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemThuocLayout.createSequentialGroup()
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addComponent(labelHinhThuoc)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addComponent(btnChonHinhanhThuoc)
                                .addGap(2, 2, 2))))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTenThuoc))
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelMota)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDonvitinhThuoc)
                            .addComponent(txtDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDonviQuydoi)
                            .addComponent(txtDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMaloaithuoc))
                        .addGap(18, 18, 18)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTileQuyDoi)
                            .addComponent(txtTiLeQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNhacungcap))
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelDotuoiThuoc))))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnhacungcapThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(giabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGiabanThuoc))))
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThuoc)
                            .addComponent(btnSua)))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnXoa)))
                .addGap(32, 32, 32))
        );

        panelDanhSachThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách thuốc"), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        tableDanhSachThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableDanhSachThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Mô tả", "Độ tuổi", "Hình ảnh", "Mã đơn vị tính", "Mã đơn vị qui đổi", "Tỉ lệ qui đổi", "Nhà cung cấp", "Loại thuốc", "Giá bán"
            }
        ));
        tableDanhSachThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachThuocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDanhSachThuoc);

        javax.swing.GroupLayout panelDanhSachThuocLayout = new javax.swing.GroupLayout(panelDanhSachThuoc);
        panelDanhSachThuoc.setLayout(panelDanhSachThuocLayout);
        panelDanhSachThuocLayout.setHorizontalGroup(
            panelDanhSachThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDanhSachThuocLayout.setVerticalGroup(
            panelDanhSachThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhSachThuocLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        jButton4.setText("Xuất file");

        btnThemFile.setText("Thêm từ file ");
        btnThemFile.setToolTipText("Thêm thuốc từ file excel");

        jButton5.setText("Tìm kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        thoatNhapThuoc.setText("Thoát");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelThemThuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDanhSachThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemFile)
                                .addGap(232, 232, 232)
                                .addComponent(thoatNhapThuoc)
                                .addGap(164, 164, 164)
                                .addComponent(jButton5)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 580, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(0, 580, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelThemThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDanhSachThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemFile)
                    .addComponent(jButton5)
                    .addComponent(thoatNhapThuoc))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 447, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(0, 448, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnhacungcapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhacungcapThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhacungcapThuocActionPerformed

    private void txtDonvitinhThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonvitinhThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonvitinhThuocActionPerformed

    private void btnChonHinhanhThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhanhThuocActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser=new JFileChooser();
        FileNameExtensionFilter filefilter= new FileNameExtensionFilter("File image","img","png","jpeg");
        fileChooser.setFileFilter(filefilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x=fileChooser.showDialog(this, "Open");
        if(x==JFileChooser.APPROVE_OPTION)
        {
            File f=fileChooser.getSelectedFile();
            if(!f.exists())
            {
                int result = JOptionPane.showConfirmDialog(this,"The file "+f.getName()+" không tồn tại","Thông báo",JOptionPane.OK_OPTION,JOptionPane.ERROR_MESSAGE);

            }
            else{
                try{

                    FileReader fr=new FileReader(f);
                    hinhanh=f.getAbsolutePath();
                    JOptionPane.showMessageDialog(this,"Mở file "+f.getName()+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    BufferedReader br= new BufferedReader(fr);
                    if(!hinhanh.equals(""))
                      {
                new SetImage().setImageLabel(labelHinhanh,hinhanh);
                     }
                    br.close();
                    fr.close();

                }

                catch(IOException e)
                {
                    JOptionPane.showMessageDialog(this,e.toString(),"Lỗi",JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_btnChonHinhanhThuocActionPerformed

    private void giabanThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giabanThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giabanThuocActionPerformed

    private void btnThemThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocActionPerformed
        // TODO add your handling code here:
        String maThuocString=txtMaThuoc.getText();
        int maThuoc=Integer.parseInt(maThuocString);
        String maThuocMoi=this.txtLoaiThuoc.getSelectedItem().toString();
        String tenThuocMoi=this.txtTenThuoc.getText();
        //String donvitinh=this.donvitinhThuoc.getItemAt()
        String motaThuocmoi=this.txtMotaThuoc.getText();
        String dongiaThuocmoiString=this.giabanThuoc.getText();
        Float dongiaThuocmoiFloat=Float.parseFloat(dongiaThuocmoiString);
        String maLoaiThuocMoi=this.txtLoaiThuoc.getSelectedItem().toString();
        Donvitinh donvitinhselected=  (Donvitinh) this.txtDonvitinhThuoc.getSelectedItem();
        Donvitinh donviQuydoiThuocSelected=(Donvitinh)this.txtDonviQuydoi.getSelectedItem();
        String tileQuydoiThuocMoi=txtTiLeQuyDoi.getText();
        String dotuoi=this.listDotuoiThuoc.getSelectedValue();
        String GiaBan=this.giabanThuoc.getText();
        
        Nhacungcap nhacungcapSelected=(Nhacungcap)txtnhacungcapThuoc.getSelectedItem();
        LoaiThuoc loaiThuocMoi=(LoaiThuoc)this.txtLoaiThuoc.getSelectedItem();
        if(maThuocMoi.equals("")||tenThuocMoi.equals("")||motaThuocmoi.equals("")||dongiaThuocmoiString.equals("")||maLoaiThuocMoi.equals("")||dongiaThuocmoiString.equals("")|dotuoi.equals("")||GiaBan.equals("")||hinhanh.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Mã thuốc, tên thuốc,mô tả, đơn giá, mã loại thuốc thuốc, đơn vị tính,đơn vị quy đổi, tỉ lệ quy đổi,độ tuổi, giá bán, hình ảnh không được để trống","Thông báo",JOptionPane.ERROR_MESSAGE);
        }

        Thuoc thuocThemVao=new Thuoc(maThuoc,tenThuocMoi,motaThuocmoi,dotuoi,hinhanh,donvitinhselected,donviQuydoiThuocSelected,Integer.parseInt(tileQuydoiThuocMoi),nhacungcapSelected,loaiThuocMoi,dongiaThuocmoiFloat);
        System.out.println(thuocThemVao);
        try {
            ThuocController.themThuoc(thuocThemVao);
            JOptionPane.showMessageDialog(this,"Thêm thuốc"+thuocThemVao.getTenThuoc()+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Thêm thuốc không thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnThemThuocActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedrow=tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc=Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsThuoc.size();i++)
        {
            if(dsThuoc.get(i).getMaThuoc()==selectedMaThuoc)
            {
                selected=i;
            }
        }
        String maThuocString=txtMaThuoc.getText();
        int maThuoc=Integer.parseInt(maThuocString);
        String maThuocMoi=this.txtLoaiThuoc.getSelectedItem().toString();
        String tenThuocMoi=this.txtTenThuoc.getText();
        //String donvitinh=this.donvitinhThuoc.getItemAt()
        String motaThuocmoi=this.txtMotaThuoc.getText();
        Nhacungcap nhacungcap=(Nhacungcap)txtnhacungcapThuoc.getSelectedItem();
        Donvitinh donvitinhThuocMoi=(Donvitinh)this.txtDonvitinhThuoc.getSelectedItem();
        Donvitinh donviQuidoiThuocMoi=(Donvitinh)this.txtDonviQuydoi.getSelectedItem();
        int tileQuidoi=Integer.parseInt(txtTiLeQuyDoi.getText());
        String dotuoi=this.listDotuoiThuoc.getSelectedValue();
        String GiaBan=this.giabanThuoc.getText();
        Float giaBanThuocMoi=Float.parseFloat(this.giabanThuoc.getText());
        LoaiThuoc loaiThuoc=(LoaiThuoc)this.txtLoaiThuoc.getSelectedItem();
        
        if(maThuocMoi.equals("")||tenThuocMoi.equals("")||motaThuocmoi.equals("")||giaBanThuocMoi.equals("")||loaiThuoc.equals("")||giaBanThuocMoi.equals("")|dotuoi.equals("")||GiaBan.equals("")||hinhanh.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Mã thuốc, tên thuốc,mô tả, đơn giá, mã thuốc, đơn vị tính,độ tuổi, giá bán, hình ảnh không được để trống","Thông báo",JOptionPane.ERROR_MESSAGE);
        }

        Thuoc thuocCapNhat=new Thuoc(maThuoc,tenThuocMoi,motaThuocmoi,dotuoi,hinhanh,donvitinhThuocMoi,donviQuidoiThuocMoi,tileQuidoi,nhacungcap,loaiThuoc,giaBanThuocMoi);
        int maThuocCu=(dsThuoc.get(selected).getMaThuoc());
        try {
            ThuocController.capnhatThuoc(thuocCapNhat,maThuocCu);
            JOptionPane.showMessageDialog(this,"Cap nhat thuốc"+ thuocCapNhat.getTenThuoc()+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Cập nhật thuốc không thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedrow=tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc=Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsThuoc.size();i++)
        {
            if(dsThuoc.get(i).getMaThuoc()==selectedMaThuoc)
            {
                selected=i;
            }
        }
        int maThuoc=dsThuoc.get(selected).getMaThuoc();
        try {
            ThuocController.xoaThuoc(maThuoc);
            JOptionPane.showMessageDialog(this,"Xóa thuốc"+dsThuoc.get(selected).getTenThuoc()+" thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Xóa thuốc"+dsThuoc.get(selected).getTenThuoc()+" không thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ShowData();
    }//GEN-LAST:event_btnXoaActionPerformed
    
    private void tableDanhSachThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachThuocMouseClicked
        // TODO add your handling code here:
        int selectedrow=tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc=Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow,0).toString());
        int selected=-1;
        for(int i=0;i<dsThuoc.size();i++)
        {
            if(dsThuoc.get(i).getMaThuoc()==selectedMaThuoc)
            {
                selected=i;
            }
        }
        if(selected>=0)
        {
            txtMaThuoc.setText(String.valueOf(dsThuoc.get(selected).getMaThuoc()));
            txtTenThuoc.setText(dsThuoc.get(selected).getTenThuoc());
            txtMotaThuoc.setText(dsThuoc.get(selected).getMota());
            giabanThuoc.setText(String.valueOf(dsThuoc.get(selected).getGiaBan()));
            //DefaultComboBoxModel modelLoaiThuoc=new DefaultComboBoxModel(new String[]{String.valueOf(dsThuoc.get(selected).getLoaiThuoc())});
            DefaultComboBoxModel modelLoaiThuoc=(DefaultComboBoxModel) txtLoaiThuoc.getModel();
             
            for(int i=0;i<modelLoaiThuoc.getSize();i++)
            {
                 LoaiThuoc loaiThuoc=(LoaiThuoc) modelLoaiThuoc.getElementAt(i);
                if(loaiThuoc.getMaLoaiThuoc()==(dsThuoc.get(selected).getLoaiThuoc()).getMaLoaiThuoc())
                {
                    txtLoaiThuoc.setSelectedIndex(i);
                    break;
                }
            }
            //txtLoaiThuoc.setModel(modelLoaiThuoc);
//            DefaultComboBoxModel ModelDonvitinh=new DefaultComboBoxModel(new String[]{String.valueOf(dsThuoc.get(selected).getDonvitinh())});
//            txtDonvitinhThuoc.setModel(ModelDonvitinh);
            DefaultComboBoxModel modelDonvitinh=(DefaultComboBoxModel) txtDonvitinhThuoc.getModel();
             
            for(int i=0;i<modelDonvitinh.getSize();i++)
            {
                 Donvitinh donvitinh=(Donvitinh) modelLoaiThuoc.getElementAt(i);
                if(donvitinh.getMaDonvitinh()==(dsThuoc.get(selected).getDonvitinh()).getMaDonvitinh())
                {
                    txtDonvitinhThuoc.setSelectedIndex(i);
                    break;
                }
            }
            DefaultComboBoxModel modelDonviQuiDoi=(DefaultComboBoxModel) txtDonviQuydoi.getModel();
             
            for(int i=0;i<modelDonviQuiDoi.getSize();i++)
            {
                 Donvitinh donviQuiDoi=(Donvitinh) modelDonviQuiDoi.getElementAt(i);
                if(donviQuiDoi.getMaDonvitinh()==(dsThuoc.get(selected).getDonviQuydoi()).getMaDonvitinh())
                {
                    txtDonviQuydoi.setSelectedIndex(i);
                    break;
                }
            }
            txtTiLeQuyDoi.setText(String.valueOf(dsThuoc.get(selected).getTileQuydoi()));
            String linkHinhAnh=dsThuoc.get(selected).getHinhanh();
            if(!linkHinhAnh.equals(""))
            {
                new SetImage().setImageLabel(labelHinhanh,linkHinhAnh);
            }
                    
        }
    }//GEN-LAST:event_tableDanhSachThuocMouseClicked

    private void panelThemThuocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelThemThuocKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A)
        {
            JOptionPane.showMessageDialog(this,"Bạn vừa nhấn phím: "+evt.getKeyChar());
        }
    }//GEN-LAST:event_panelThemThuocKeyTyped

    private void panelThemThuocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelThemThuocKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelThemThuocKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTiLeQuyDoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiLeQuyDoiKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       
        if(!(Character.isDigit(c))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
        {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtTiLeQuyDoiKeyTyped

    private void giabanThuocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_giabanThuocKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        //|| c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL 
        if(!(Character.isDigit(c))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE )
        {
            System.out.println(c);
            evt.consume();
        }
    }//GEN-LAST:event_giabanThuocKeyTyped

     public void ShowData()
    {
        DefaultTableModel tblModel=(DefaultTableModel) tableDanhSachThuoc.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
       dsThuoc=ThuocController.getDanhSachThuoc();
        if(!dsThuoc.isEmpty()){
                dsThuoc.forEach((thuoc1)->{
                 if(!thuoc1.isDaXoa())
                 {
                tblModel.addRow(new Object[]{thuoc1.getMaThuoc(),thuoc1.getTenThuoc(),thuoc1.getMota(),thuoc1.getDotuoi(),thuoc1.getHinhanh(),thuoc1.getDonvitinh(),thuoc1.getDonviQuydoi(),thuoc1.getTileQuydoi(),thuoc1.getNhacungcap(),thuoc1.getLoaiThuoc(),thuoc1.getGiaBan()});
                 }
                });
        }
        else
        {
          JOptionPane.showMessageDialog(this,"Danh sách thuốc rỗng","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }
     public void showLoaiThuoc()
     {
      DefaultComboBoxModel loaiThuocModel=(DefaultComboBoxModel) txtLoaiThuoc.getModel();
      loaiThuocModel.removeAllElements();
        ArrayList<LoaiThuoc> danhsachLoaiThuoc= LoaiThuocController.getDanhSachLoaiThuoc();
        danhsachLoaiThuoc.forEach(LoaiThuoc->{
            loaiThuocModel.addElement(LoaiThuoc);
        });        
         
     }
     public void showDonvitinh()
     {
          DefaultComboBoxModel DonvitinhThuocModel=(DefaultComboBoxModel) txtDonvitinhThuoc.getModel();
      DonvitinhThuocModel.removeAllElements();
        ArrayList<Donvitinh> donvitinhs= DonvitinhController.getDanhSachDonvitinh();
        donvitinhs.forEach(donvitinh->{
            DonvitinhThuocModel.addElement(donvitinh);
        });        
     }
     public void showDonviQuydoi()
     {
          DefaultComboBoxModel DonvitinhThuocModel=(DefaultComboBoxModel) txtDonviQuydoi.getModel();
      DonvitinhThuocModel.removeAllElements();
        ArrayList<Donvitinh> donvitinhs= DonvitinhController.getDanhSachDonvitinh();
        donvitinhs.forEach(donvitinh->{
            DonvitinhThuocModel.addElement(donvitinh);
        });        
     }
     public void showNhacungcap()
     {
         DefaultComboBoxModel nhacungcapComboBoxModel=(DefaultComboBoxModel) txtnhacungcapThuoc.getModel();
         nhacungcapComboBoxModel.removeAllElements();
         ArrayList<Nhacungcap> dsNhacungcap=NhacungcapController.getDanhSachNhacungcap();
         dsNhacungcap.forEach(Nhacungcap->{
         nhacungcapComboBoxModel.addElement(Nhacungcap);
     });
     }
     public void showDotuoiThuoc()
     {
         DefaultListModel DotuoiThuocModel = new  DefaultListModel();
        
        //this.sDefaultListModel DotuoiThuocModel = new DefaultListModel();etIconImage();
        DotuoiThuocModel.removeAllElements();
                DotuoiThuocModel.addElement("Nhỏ hơn 2 tuổi");
                DotuoiThuocModel.addElement("Từ 2 đến 5 tuổi");
                DotuoiThuocModel.addElement("Từ 5 tới 12 tuổi");
                DotuoiThuocModel.addElement("Từ 13 tới 16 tuổi");
                DotuoiThuocModel.addElement("Từ 16 tuổi trở lên");
        listDotuoiThuoc.setModel(DotuoiThuocModel);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinhanhThuoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemFile;
    private javax.swing.JButton btnThemThuoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JTextField giabanThuoc;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDonviQuydoi;
    private javax.swing.JLabel labelDonvitinhThuoc;
    private javax.swing.JLabel labelDotuoiThuoc;
    private javax.swing.JLabel labelGiabanThuoc;
    private javax.swing.JLabel labelHinhThuoc;
    private javax.swing.JLabel labelHinhanh;
    private javax.swing.JLabel labelMaloaithuoc;
    private javax.swing.JLabel labelMota;
    private javax.swing.JLabel labelNhacungcap;
    private javax.swing.JLabel labelTenThuoc;
    private javax.swing.JLabel labelTileQuyDoi;
    private javax.swing.JList<String> listDotuoiThuoc;
    private javax.swing.JPanel panelDanhSachThuoc;
    private javax.swing.JPanel panelThemThuoc;
    private javax.swing.JTable tableDanhSachThuoc;
    private javax.swing.JButton thoatNhapThuoc;
    private javax.swing.JComboBox<String> txtDonviQuydoi;
    private javax.swing.JComboBox<String> txtDonvitinhThuoc;
    private javax.swing.JComboBox<String> txtLoaiThuoc;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextArea txtMotaThuoc;
    private javax.swing.JTextField txtTenThuoc;
    private javax.swing.JTextField txtTiLeQuyDoi;
    private javax.swing.JComboBox<String> txtnhacungcapThuoc;
    // End of variables declaration//GEN-END:variables
}