package Views;

import Components.AutoCompletion;
import Components.ReadExcelNhacungcap;
import Components.ReadExcelThuoc;
import Controllers.DonvitinhController;
import Controllers.ThuocController;
import Controllers.LoaithuocController;
import javax.swing.DefaultListModel;
import Models.Donvitinh;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Controllers.ThuocController;
import Models.Thuoc;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import Components.SetImage;
import Components.WriteExcelNhacungcap;
import Components.WriteExcelThuoc;
import Controllers.NhacungcapController;
import Models.LoaiThuoc;
import Models.Nhacungcap;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

public class ThuocView extends javax.swing.JPanel {

    String hinhanh = "";
    ArrayList<Thuoc> dsThuoc;

    public ThuocView() {
        initComponents();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachThuoc.setDefaultRenderer(String.class, centerRenderer);
        for (int i = 0; i < tableDanhSachThuoc.getColumnCount(); i++) {
    tableDanhSachThuoc.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
}
        
        ((DefaultTableCellRenderer) tableDanhSachThuoc.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tableDanhSachThuoc.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        tableDanhSachThuoc.getTableHeader().setOpaque(false);
        tableDanhSachThuoc.getTableHeader().setBackground(Color.YELLOW);
        tableDanhSachThuoc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         tableDanhSachThuoc.setUpdateSelectionOnSort(true);
        tableDanhSachThuoc.setFillsViewportHeight(true);
        if (!DangnhapView.quyenLogin.getChitietQuyen().contains("qlThuoc")) {
            btnThemThuoc.setEnabled(false);
            btnThemFile.setEnabled(false);
            btnXuatFile.setEnabled(false);
        }
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        txtMaThuoc.setEditable(false);

        ShowData();
        showLoaiThuoc();
        showDonvitinh();
        showDonviQuydoi();
        showNhacungcap();
        showDotuoiThuoc();
        ShowSearchComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThemThuoc = new javax.swing.JPanel();
        labelMaloaithuoc = new javax.swing.JLabel();
        txtLoaiThuoc = new javax.swing.JComboBox<>();
        labelTenThuoc = new javax.swing.JLabel();
        txtTenThuoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotaThuoc = new javax.swing.JTextArea();
        labelMota = new javax.swing.JLabel();
        txtnhacungcapThuoc = new javax.swing.JComboBox<>();
        labelNhacungcap = new javax.swing.JLabel();
        txtDonvitinhThuoc = new javax.swing.JComboBox<>();
        labelDonvitinhThuoc = new javax.swing.JLabel();
        btnChonHinhanhThuoc = new javax.swing.JButton();
        labelHinhThuoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDotuoiThuoc = new javax.swing.JList<>();
        labelDotuoiThuoc = new javax.swing.JLabel();
        giabanThuoc = new javax.swing.JTextField();
        labelGiabanThuoc = new javax.swing.JLabel();
        btnThemThuoc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelHinhanh = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaThuoc = new javax.swing.JTextField();
        txtDonviQuydoi = new javax.swing.JComboBox<>();
        labelDonviQuydoi = new javax.swing.JLabel();
        txtTiLeQuyDoi = new javax.swing.JTextField();
        labelTileQuyDoi = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        panelDanhSachThuoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDanhSachThuoc = new javax.swing.JTable();
        btnThemFile = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchBox = new com.raven.chart.TextFieldSuggestion();

        panelThemThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        panelThemThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelThemThuocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelThemThuocKeyTyped(evt);
            }
        });

        labelMaloaithuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMaloaithuoc.setText("Mã loại thuốc");

        txtLoaiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        labelTenThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTenThuoc.setText("Tên thuốc");

        txtTenThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtMotaThuoc.setColumns(5);
        txtMotaThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMotaThuoc.setRows(5);
        jScrollPane2.setViewportView(txtMotaThuoc);

        labelMota.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelMota.setText("Mô tả");

        txtnhacungcapThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtnhacungcapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhacungcapThuocActionPerformed(evt);
            }
        });

        labelNhacungcap.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelNhacungcap.setText("Nhà cung cấp");

        txtDonvitinhThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDonvitinhThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonvitinhThuocActionPerformed(evt);
            }
        });

        labelDonvitinhThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDonvitinhThuoc.setText("Đơn vị tính");

        btnChonHinhanhThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnChonHinhanhThuoc.setText("Chọn hình ảnh");
        btnChonHinhanhThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhanhThuocActionPerformed(evt);
            }
        });

        labelHinhThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelHinhThuoc.setText("Hình ảnh");

        listDotuoiThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(listDotuoiThuoc);

        labelDotuoiThuoc.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDotuoiThuoc.setText("Độ tuổi");

        giabanThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        giabanThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giabanThuocActionPerformed(evt);
            }
        });
        giabanThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                giabanThuocKeyTyped(evt);
            }
        });

        labelGiabanThuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelGiabanThuoc.setText("Giá bán");

        btnThemThuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThemThuoc.setText("Thêm thuốc");
        btnThemThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ảnh Thuốc"));

        labelHinhanh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHinhanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_database_restore_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_30px_1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Mã thuốc");

        txtMaThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDonviQuydoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        labelDonviQuydoi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelDonviQuydoi.setText("Đơn vị quy đổi");

        txtTiLeQuyDoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTiLeQuyDoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiLeQuyDoiKeyTyped(evt);
            }
        });

        labelTileQuyDoi.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTileQuyDoi.setText("Tỉ lệ quy đổi");

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(0, 255, 0));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 0, 0));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThemThuocLayout = new javax.swing.GroupLayout(panelThemThuoc);
        panelThemThuoc.setLayout(panelThemThuocLayout);
        panelThemThuocLayout.setHorizontalGroup(
            panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemThuocLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtTenThuoc)
                                    .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addComponent(btnThemThuoc)
                                .addGap(130, 130, 130)
                                .addComponent(btnHuy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu)
                                .addGap(53, 53, 53)))
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(labelTileQuyDoi)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTiLeQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelDotuoiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addComponent(labelMaloaithuoc)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addComponent(labelHinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelGiabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonHinhanhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnXoa))
                    .addComponent(giabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnhacungcapThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(264, 264, 264))
        );
        panelThemThuocLayout.setVerticalGroup(
            panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemThuocLayout.createSequentialGroup()
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHinhThuoc)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                        .addComponent(btnChonHinhanhThuoc)
                                        .addGap(2, 2, 2))))
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMaloaithuoc)
                            .addComponent(labelDonvitinhThuoc)
                            .addComponent(txtDonvitinhThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnhacungcapThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNhacungcap))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThemThuocLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTenThuoc))
                                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(labelMota)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemThuocLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDotuoiThuoc)
                                .addGap(129, 129, 129)))
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonviQuydoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDonviQuydoi))
                        .addGap(18, 18, 18)))
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giabanThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGiabanThuoc)
                    .addComponent(txtTiLeQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTileQuyDoi))
                .addGap(9, 9, 9)
                .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThuoc)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelThemThuocLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelThemThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))))
                .addGap(30, 30, 30))
        );

        panelDanhSachThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách thuốc"), "Danh sách thuốc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        tableDanhSachThuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableDanhSachThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Mô tả", "Độ tuổi", "Hình ảnh", "Mã đơn vị tính", "Mã đơn vị qui đổi", "Tỉ lệ qui đổi", "Nhà cung cấp", "Loại thuốc", "Giá bán"
            }
        ));
        tableDanhSachThuoc.setRowHeight(30);
        tableDanhSachThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDanhSachThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableDanhSachThuocMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tableDanhSachThuoc);

        javax.swing.GroupLayout panelDanhSachThuocLayout = new javax.swing.GroupLayout(panelDanhSachThuoc);
        panelDanhSachThuoc.setLayout(panelDanhSachThuocLayout);
        panelDanhSachThuocLayout.setHorizontalGroup(
            panelDanhSachThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
        );
        panelDanhSachThuocLayout.setVerticalGroup(
            panelDanhSachThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        btnThemFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_ms_excel_30px.png"))); // NOI18N
        btnThemFile.setText("Thêm từ file ");
        btnThemFile.setToolTipText("Thêm thuốc từ file excel");
        btnThemFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemFileActionPerformed(evt);
            }
        });

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_downloads_30px.png"))); // NOI18N
        btnXuatFile.setText("Xuất File");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Thông tin tìm kiếm");

        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDanhSachThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelThemThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThemFile)
                        .addGap(44, 44, 44)
                        .addComponent(btnXuatFile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelThemThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDanhSachThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatFile)
                    .addComponent(btnThemFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnhacungcapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhacungcapThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhacungcapThuocActionPerformed

    private void txtDonvitinhThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonvitinhThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonvitinhThuocActionPerformed

    private void btnChonHinhanhThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhanhThuocActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("File image", "img", "png", "jpeg");
        fileChooser.setFileFilter(filefilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Open");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            if (!f.exists()) {
                int result = JOptionPane.showConfirmDialog(this, "The file " + f.getName() + " không tồn tại", "Thông báo", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

            } else {
                try {

                    FileReader fr = new FileReader(f);
                    hinhanh = f.getAbsolutePath();
                    JOptionPane.showMessageDialog(this, "Mở file " + f.getName() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    BufferedReader br = new BufferedReader(fr);
                    if (!hinhanh.equals("")) {
                        new SetImage().setImageLabel(labelHinhanh, hinhanh);
                    }
                    br.close();
                    fr.close();

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_btnChonHinhanhThuocActionPerformed

    private void giabanThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giabanThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giabanThuocActionPerformed

    private void btnThemThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocActionPerformed
        // TODO add your handling code here:
        txtMaThuoc.setText(String.valueOf(getMaThuocMoi()));
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
        btnThemThuoc.setEnabled(false);
        txtMaThuoc.setEnabled(true);


    }//GEN-LAST:event_btnThemThuocActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc = Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsThuoc.size(); i++) {
            if (dsThuoc.get(i).getMaThuoc() == selectedMaThuoc) {
                selected = i;
            }
        }
        String maThuocString = txtMaThuoc.getText();
        int maThuoc = Integer.parseInt(maThuocString);
        String maThuocMoi = this.txtLoaiThuoc.getSelectedItem().toString();
        String tenThuocMoi = this.txtTenThuoc.getText();
        //String donvitinh=this.donvitinhThuoc.getItemAt()
        String motaThuocmoi = this.txtMotaThuoc.getText();
        Nhacungcap nhacungcap = (Nhacungcap) txtnhacungcapThuoc.getSelectedItem();
        Donvitinh donvitinhThuocMoi = (Donvitinh) this.txtDonvitinhThuoc.getSelectedItem();
        Donvitinh donviQuidoiThuocMoi = (Donvitinh) this.txtDonviQuydoi.getSelectedItem();
        int tileQuidoi = Integer.parseInt(txtTiLeQuyDoi.getText());
        String dotuoi = this.listDotuoiThuoc.getSelectedValue();
        String GiaBan = this.giabanThuoc.getText();
        Float giaBanThuocMoi = Float.parseFloat(this.giabanThuoc.getText());
        LoaiThuoc loaiThuoc = (LoaiThuoc) this.txtLoaiThuoc.getSelectedItem();

        if (maThuocMoi.equals("") || tenThuocMoi.equals("") || motaThuocmoi.equals("") || giaBanThuocMoi.equals("") || loaiThuoc.equals("") || giaBanThuocMoi.equals("") | dotuoi.equals("") || GiaBan.equals("") || hinhanh.equals("")) {
            JOptionPane.showMessageDialog(null, "Mã thuốc, tên thuốc,mô tả, đơn giá, mã thuốc, đơn vị tính,độ tuổi, giá bán, hình ảnh không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

        Thuoc thuocCapNhat = new Thuoc(maThuoc, tenThuocMoi, motaThuocmoi, dotuoi, hinhanh, donvitinhThuocMoi, donviQuidoiThuocMoi, tileQuidoi, nhacungcap, loaiThuoc, giaBanThuocMoi);
        int maThuocCu = (dsThuoc.get(selected).getMaThuoc());
        try {
            ThuocController.capnhatThuoc(thuocCapNhat, maThuocCu);
            JOptionPane.showMessageDialog(this, "Cap nhat thuốc" + thuocCapNhat.getTenThuoc() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cập nhật thuốc không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedrow = tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc = Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsThuoc.size(); i++) {
            if (dsThuoc.get(i).getMaThuoc() == selectedMaThuoc) {
                selected = i;
            }
        }
        int maThuoc = dsThuoc.get(selected).getMaThuoc();
        try {
            ThuocController.xoaThuoc(maThuoc);
            JOptionPane.showMessageDialog(this, "Xóa thuốc" + dsThuoc.get(selected).getTenThuoc() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();
            btnXoa.setEnabled(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa thuốc" + dsThuoc.get(selected).getTenThuoc() + " không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableDanhSachThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachThuocMouseClicked
        // TODO add your handling code here:
        int selectedrow = tableDanhSachThuoc.getSelectedRow();
        int selectedMaThuoc = Integer.parseInt(tableDanhSachThuoc.getModel().getValueAt(selectedrow, 0).toString());
        int selected = -1;
        for (int i = 0; i < dsThuoc.size(); i++) {
            if (dsThuoc.get(i).getMaThuoc() == selectedMaThuoc) {
                selected = i;
            }
        }
        if (selected >= 0) {
            txtMaThuoc.setText(String.valueOf(dsThuoc.get(selected).getMaThuoc()));
            txtTenThuoc.setText(dsThuoc.get(selected).getTenThuoc());
            txtMotaThuoc.setText(dsThuoc.get(selected).getMota());
            giabanThuoc.setText(String.valueOf(dsThuoc.get(selected).getGiaBan()));
            //DefaultComboBoxModel modelLoaiThuoc=new DefaultComboBoxModel(new String[]{String.valueOf(dsThuoc.get(selected).getLoaiThuoc())});
            DefaultComboBoxModel modelLoaiThuoc = (DefaultComboBoxModel) txtLoaiThuoc.getModel();

            for (int i = 0; i < modelLoaiThuoc.getSize(); i++) {
                LoaiThuoc loaiThuoc = (LoaiThuoc) modelLoaiThuoc.getElementAt(i);
                if (loaiThuoc.getMaLoaiThuoc() == (dsThuoc.get(selected).getLoaiThuoc()).getMaLoaiThuoc()) {
                    txtLoaiThuoc.setSelectedIndex(i);
                    break;
                }
            }

            DefaultComboBoxModel modelDonvitinh = (DefaultComboBoxModel) txtDonvitinhThuoc.getModel();

            for (int i = 0; i < modelDonvitinh.getSize(); i++) {
                Donvitinh donvitinh = (Donvitinh) modelDonvitinh.getElementAt(i);
                if (donvitinh.getMaDonvitinh() == (dsThuoc.get(selected).getDonvitinh()).getMaDonvitinh()) {

                    txtDonvitinhThuoc.setSelectedIndex(i);
                    break;
                }
            }
            DefaultComboBoxModel modelDonviQuiDoi = (DefaultComboBoxModel) txtDonviQuydoi.getModel();

            for (int i = 0; i < modelDonviQuiDoi.getSize(); i++) {
                Donvitinh donviQuiDoi = (Donvitinh) modelDonviQuiDoi.getElementAt(i);
                if (donviQuiDoi.getMaDonvitinh() == (dsThuoc.get(selected).getDonviQuydoi()).getMaDonvitinh()) {
                    txtDonviQuydoi.setSelectedIndex(i);
                    break;
                }
            }
            txtTiLeQuyDoi.setText(String.valueOf(dsThuoc.get(selected).getTileQuydoi()));
            DefaultListModel dotuoiModel = (DefaultListModel) listDotuoiThuoc.getModel();
            for (int i = 0; i < dotuoiModel.getSize(); i++) {
                if (dotuoiModel.get(i).equals(dsThuoc.get(selected).getDotuoi())) {
                    listDotuoiThuoc.setSelectedIndex(i);
                    break;
                }
            }
            String linkHinhAnh = dsThuoc.get(selected).getHinhanh();
            if (!linkHinhAnh.equals("")) {
                new SetImage().setImageLabel(labelHinhanh, linkHinhAnh);

            }

        }
        txtMaThuoc.setEnabled(false);
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnHuy.setEnabled(true);

    }//GEN-LAST:event_tableDanhSachThuocMouseClicked

    private void panelThemThuocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelThemThuocKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_A) {
            JOptionPane.showMessageDialog(this, "Bạn vừa nhấn phím: " + evt.getKeyChar());
        }
    }//GEN-LAST:event_panelThemThuocKeyTyped

    private void panelThemThuocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelThemThuocKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelThemThuocKeyPressed

    private void txtTiLeQuyDoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiLeQuyDoiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtTiLeQuyDoiKeyTyped

    private void giabanThuocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_giabanThuocKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        //|| c==KeyEvent.VK_PERIOD||c==KeyEvent.VK_DECIMAL 
        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            System.out.println(c);
            evt.consume();
        }
    }//GEN-LAST:event_giabanThuocKeyTyped

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maThuocString = txtMaThuoc.getText();
        int maThuoc = Integer.parseInt(maThuocString);
        String maThuocMoi = this.txtLoaiThuoc.getSelectedItem().toString();
        String tenThuocMoi = this.txtTenThuoc.getText();
        //String donvitinh=this.donvitinhThuoc.getItemAt()
        String motaThuocmoi = this.txtMotaThuoc.getText();
        String dongiaThuocmoiString = this.giabanThuoc.getText();
        Float dongiaThuocmoiFloat = Float.parseFloat(dongiaThuocmoiString);
        String maLoaiThuocMoi = this.txtLoaiThuoc.getSelectedItem().toString();
        Donvitinh donvitinhselected = (Donvitinh) this.txtDonvitinhThuoc.getSelectedItem();
        Donvitinh donviQuydoiThuocSelected = (Donvitinh) this.txtDonviQuydoi.getSelectedItem();
        String tileQuydoiThuocMoi = txtTiLeQuyDoi.getText();
        String dotuoi = this.listDotuoiThuoc.getSelectedValue();
        String GiaBan = this.giabanThuoc.getText();
        Nhacungcap nhacungcapSelected = (Nhacungcap) txtnhacungcapThuoc.getSelectedItem();
        LoaiThuoc loaiThuocMoi = (LoaiThuoc) this.txtLoaiThuoc.getSelectedItem();
        if (maThuocMoi.equals("") || maThuocMoi.equals(null) || tenThuocMoi.equals("") || tenThuocMoi.equals(null) || motaThuocmoi.equals("") || motaThuocmoi.equals(null) || dongiaThuocmoiString.equals("") || dongiaThuocmoiString.equals(null) || maLoaiThuocMoi.equals("") || maLoaiThuocMoi.equals(null) || dongiaThuocmoiString.equals("") || dongiaThuocmoiString.equals(null) | dotuoi.equals("") || dotuoi.equals(null) || GiaBan.equals("") || GiaBan.equals(null) || hinhanh.equals("") || hinhanh.equals(null)) {
            JOptionPane.showMessageDialog(null, "Mã thuốc, tên thuốc,mô tả, đơn giá, mã loại thuốc thuốc, đơn vị tính,đơn vị quy đổi, tỉ lệ quy đổi,độ tuổi, giá bán, hình ảnh không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Thuoc thuocThemVao = new Thuoc(maThuoc, tenThuocMoi, motaThuocmoi, dotuoi, hinhanh, donvitinhselected, donviQuydoiThuocSelected, Integer.parseInt(tileQuydoiThuocMoi), nhacungcapSelected, loaiThuocMoi, dongiaThuocmoiFloat);
        try {
            ThuocController.themThuoc(thuocThemVao);
            JOptionPane.showMessageDialog(this, "Thêm thuốc" + thuocThemVao.getTenThuoc() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ShowData();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm thuốc " + thuocThemVao.getTenThuoc() + " không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn hủy hay không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            if (input == 0) {
                txtMaThuoc.setText("");
                txtTenThuoc.setText("");
                txtMotaThuoc.setText("");
                txtTiLeQuyDoi.setText("");
                hinhanh = "";
                labelHinhanh.setIcon(null);
                giabanThuoc.setText("");
                btnHuy.setEnabled(false);
                btnLuu.setEnabled(false);
                btnSua.setEnabled(false);
                btnThemThuoc.setEnabled(true);
                tableDanhSachThuoc.getSelectionModel().clearSelection();

            }
        }


    }//GEN-LAST:event_btnHuyActionPerformed

    private void tableDanhSachThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDanhSachThuocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDanhSachThuocMouseEntered

    private void btnThemFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("File excel", "xlsx", "xls", "csv");
        fileChooser.setFileFilter(filefilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Open");

        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.exists()) {
                int result = JOptionPane.showConfirmDialog(this, "The file " + file.getName() + " không tồn tại", "Thông báo", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

            } else {
                try {

                    ReadExcelThuoc c = new ReadExcelThuoc();
                    ArrayList<Thuoc> dsThuocs = c.readExcel(file.getAbsolutePath());
                    dsThuocs.forEach(Thuoc -> {
                        try {
                            ThuocController.themThuoc(Thuoc);
                        } catch (Exception ex) {
                            Logger.getLogger(NhacungcapView.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                    JOptionPane.showMessageDialog(this, "Thêm danh sách nhà cung cấp từ file: " + file.getAbsolutePath() + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ShowData();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btnThemFileActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        WriteExcelThuoc writeExcelThuoc = new WriteExcelThuoc();
        final List<Thuoc> thuocs = ThuocController.getDanhSachThuoc();
        JFileChooser fchoose = new JFileChooser();
        int option = fchoose.showOpenDialog(fchoose);
        if (option == JFileChooser.APPROVE_OPTION) {
            String name = fchoose.getSelectedFile().getName();
            String path = fchoose.getSelectedFile().getParentFile().getPath();
            String file = path + "\\" + name + ".xlsx";
            final String excelFilePath = file;
            try {
                writeExcelThuoc.writeExcel(thuocs, excelFilePath);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
          String searchText = txtSearchBox.getText();
        if(searchText.equals("")||searchText.equals(null))
        {
            ShowData();
        }
        else
        {
        DefaultTableModel tblModel = (DefaultTableModel) tableDanhSachThuoc.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
        if(dsThuoc==null)
        {
            ShowData();
        }
        //dsThuoc = ThuocController.timkiemThuoc(searchText.toLowerCase());
        if (!dsThuoc.isEmpty()) {
            dsThuoc.forEach((thuoc1) -> {
               if (!thuoc1.isDaXoa()&&(String.valueOf(thuoc1.getMaThuoc()).contains(searchText)||thuoc1.getTenThuoc().contains(searchText)||thuoc1.getMota().contains(searchText)||thuoc1.getNhacungcap().getTenNhacungcap().contains(searchText)||thuoc1.getDotuoi().contains(searchText)||thuoc1.getDonvitinh().getTenDonvitinh().contains(searchText)||thuoc1.getDonviQuydoi().getTenDonvitinh().contains(searchText))) {
                    tblModel.addRow(new Object[]{thuoc1.getMaThuoc(), thuoc1.getTenThuoc(), thuoc1.getMota(), thuoc1.getDotuoi(), thuoc1.getHinhanh(), thuoc1.getDonvitinh().getMaDonvitinh(), thuoc1.getDonviQuydoi().getMaDonvitinh(), thuoc1.getTileQuydoi(), thuoc1.getNhacungcap(), thuoc1.getLoaiThuoc(), thuoc1.getGiaBan()});
                }
            });
        } else {
            JOptionPane.showMessageDialog(this, "Danh sách nhà cung cấp rỗng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtSearchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyPressed
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(c==KeyEvent.VK_ENTER)
        {
            btnTimKiem.doClick();
        }
    }//GEN-LAST:event_txtSearchBoxKeyPressed

    public void ShowData() {
        DefaultTableModel tblModel = (DefaultTableModel) tableDanhSachThuoc.getModel();
        tblModel.getDataVector().removeAllElements();
        tblModel.fireTableDataChanged();
        dsThuoc = ThuocController.getDanhSachThuoc();
        if (!dsThuoc.isEmpty()) {
            dsThuoc.forEach((thuoc1) -> {
                if (!thuoc1.isDaXoa()) {
                    tblModel.addRow(new Object[]{thuoc1.getMaThuoc(), thuoc1.getTenThuoc(), thuoc1.getMota(), thuoc1.getDotuoi(), thuoc1.getHinhanh(), thuoc1.getDonvitinh().getMaDonvitinh(), thuoc1.getDonviQuydoi().getMaDonvitinh(), thuoc1.getTileQuydoi(), thuoc1.getNhacungcap(), thuoc1.getLoaiThuoc(), thuoc1.getGiaBan()});
                }
            });
        } else {
            JOptionPane.showMessageDialog(this, "Danh sách thuốc rỗng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        }
        tableDanhSachThuoc.setAutoCreateRowSorter(true);
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        txtMaThuoc.setEditable(false);
        btnThemThuoc.setEnabled(true);
    }

    public void showLoaiThuoc() {
        DefaultComboBoxModel loaiThuocModel = (DefaultComboBoxModel) txtLoaiThuoc.getModel();
        loaiThuocModel.removeAllElements();
        ArrayList<LoaiThuoc> danhsachLoaiThuoc = LoaithuocController.getDanhSachLoaiThuoc();
        danhsachLoaiThuoc.forEach(LoaiThuoc -> {
            loaiThuocModel.addElement(LoaiThuoc);
        });

    }

    public void showDonvitinh() {
        DefaultComboBoxModel DonvitinhThuocModel = (DefaultComboBoxModel) txtDonvitinhThuoc.getModel();
        DonvitinhThuocModel.removeAllElements();
        ArrayList<Donvitinh> donvitinhs = DonvitinhController.getDanhSachDonvitinh();
        donvitinhs.forEach(donvitinh -> {
            DonvitinhThuocModel.addElement(donvitinh);
        });
    }

    public void showDonviQuydoi() {
        DefaultComboBoxModel DonvitinhThuocModel = (DefaultComboBoxModel) txtDonviQuydoi.getModel();
        DonvitinhThuocModel.removeAllElements();
        ArrayList<Donvitinh> donvitinhs = DonvitinhController.getDanhSachDonvitinh();
        donvitinhs.forEach(donvitinh -> {
            DonvitinhThuocModel.addElement(donvitinh);
        });
    }

    public void showNhacungcap() {
        DefaultComboBoxModel nhacungcapComboBoxModel = (DefaultComboBoxModel) txtnhacungcapThuoc.getModel();
        nhacungcapComboBoxModel.removeAllElements();
        ArrayList<Nhacungcap> dsNhacungcap = NhacungcapController.getDanhSachNhacungcap();
        dsNhacungcap.forEach(Nhacungcap -> {
            nhacungcapComboBoxModel.addElement(Nhacungcap);
        });
    }

    public void showDotuoiThuoc() {
        DefaultListModel DotuoiThuocModel = new DefaultListModel();

        //this.sDefaultListModel DotuoiThuocModel = new DefaultListModel();etIconImage();
        DotuoiThuocModel.removeAllElements();
        DotuoiThuocModel.addElement("Nhỏ hơn 2 tuổi");
        DotuoiThuocModel.addElement("Từ 2 đến 5 tuổi");
        DotuoiThuocModel.addElement("Từ 5 tới 12 tuổi");
        DotuoiThuocModel.addElement("Từ 13 tới 16 tuổi");
        DotuoiThuocModel.addElement("Từ 16 tuổi trở lên");
        listDotuoiThuoc.setModel(DotuoiThuocModel);
    }

    public int getMaThuocMoi() {
        int maThuocMoi = 0;
        for (Thuoc thuoc : dsThuoc) {
            if (thuoc.getMaThuoc() > maThuocMoi) {
                maThuocMoi = thuoc.getMaThuoc();
            }
        }
        return maThuocMoi + 1;
    }
    public void ShowSearchComboBox() {
        
        Set<String> hash_Set = new HashSet<String>();
        dsThuoc.forEach(thuoc -> {
           hash_Set.add(String.valueOf(thuoc.getMaThuoc()));
            hash_Set.add(thuoc.getTenThuoc());
             hash_Set.add(thuoc.getMota());
            hash_Set.add(thuoc.getLoaiThuoc().getTenLoaiThuoc());
             hash_Set.add(thuoc.getNhacungcap().getTenNhacungcap());
              hash_Set.add(thuoc.getDotuoi());
              hash_Set.add(thuoc.getDonvitinh().getTenDonvitinh());
              hash_Set.add(thuoc.getDonviQuydoi().getTenDonvitinh());
        }
        );
         txtSearchBox.clearItemSuggestion();
        Iterator value = hash_Set.iterator();
         while (value.hasNext()) {
            txtSearchBox.addItemSuggestion(String.valueOf(value.next()));
        }
      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinhanhThuoc;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemFile;
    private javax.swing.JButton btnThemThuoc;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JTextField giabanThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDonviQuydoi;
    private javax.swing.JLabel labelDonvitinhThuoc;
    private javax.swing.JLabel labelDotuoiThuoc;
    private javax.swing.JLabel labelGiabanThuoc;
    private javax.swing.JLabel labelHinhThuoc;
    private javax.swing.JLabel labelHinhanh;
    private javax.swing.JLabel labelMaloaithuoc;
    private javax.swing.JLabel labelMota;
    private javax.swing.JLabel labelNhacungcap;
    private javax.swing.JLabel labelTenThuoc;
    private javax.swing.JLabel labelTileQuyDoi;
    private javax.swing.JList<String> listDotuoiThuoc;
    private javax.swing.JPanel panelDanhSachThuoc;
    private javax.swing.JPanel panelThemThuoc;
    private javax.swing.JTable tableDanhSachThuoc;
    private javax.swing.JComboBox<String> txtDonviQuydoi;
    private javax.swing.JComboBox<String> txtDonvitinhThuoc;
    private javax.swing.JComboBox<String> txtLoaiThuoc;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextArea txtMotaThuoc;
    private com.raven.chart.TextFieldSuggestion txtSearchBox;
    private javax.swing.JTextField txtTenThuoc;
    private javax.swing.JTextField txtTiLeQuyDoi;
    private javax.swing.JComboBox<String> txtnhacungcapThuoc;
    // End of variables declaration//GEN-END:variables
}
