/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Controllers.DonvitinhController;
import Controllers.HuyenController;
import Controllers.TinhController;
import Controllers.XaController;
import Models.Donvitinh;
import Models.Huyen;
import Models.Tinh;
import Models.Xa;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author HauPC
 */
public class TinhHuyenXa extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public TinhHuyenXa() {
        initComponents();
        showTinh();
        showHuyen();
        showXa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void showTinh()
    {
        DefaultComboBoxModel tinhBoxModel=(DefaultComboBoxModel) txtTinh.getModel();
      tinhBoxModel.removeAllElements();
      TinhController tinhController=new TinhController();
        ArrayList<Tinh> dsTinh= tinhController.getDanhsachTinh();
        dsTinh.forEach(tinh->{
            tinhBoxModel.addElement(tinh);
        });        
    }
    public void showHuyen(){
        DefaultComboBoxModel huyenBoxModel=(DefaultComboBoxModel) txtHuyen.getModel();
      huyenBoxModel.removeAllElements();
      HuyenController huyenController=new HuyenController();
        ArrayList<Huyen> dsHuyen= huyenController.getDanhsachHuyen();
        dsHuyen.forEach(huyen->{
            huyenBoxModel.addElement(huyen);
        });      
    }
    public void showXa(){
        DefaultComboBoxModel xaBoxModel=(DefaultComboBoxModel) txtXa.getModel();
      xaBoxModel.removeAllElements();
      XaController xaController=new XaController();
        ArrayList<Xa> dsXa= xaController.getDanhsachXa();
        dsXa.forEach(xa->{
            xaBoxModel.addElement(xa);
        });       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTinh = new javax.swing.JComboBox<>();
        txtHuyen = new javax.swing.JComboBox<>();
        txtXa = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> txtHuyen;
    private javax.swing.JComboBox<String> txtTinh;
    private javax.swing.JComboBox<String> txtXa;
    // End of variables declaration//GEN-END:variables
}
